/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import basement_class.DAO.ListingHelperFunction;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_2.Account.SellerAccount;
import basement_class.Enterprise_2.Enterprise.MarketplaceEnterprise;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.ListingDirectory;
import basement_class.Enterprise_2.Organization.SellerOrganization;
import basement_class.Enterprise_2.WorkRequest.ListingSubmissionRequest;
import basement_class.Enterprise_3.WorkRequest.ListingReviewRequest;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccountDirectory;
import java.awt.Container;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;




/**
 *
 * @author 心火牧神塞勒斯
 */
public class CreateNewListingJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private SellerAccount seller;
    private SellerOrganization sellerOrg;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    /**
     * Creates new form CreateNewListingJPanel
     */
    public CreateNewListingJPanel(EcoSystem system,SellerAccount seller,SellerOrganization org) {
        initComponents();
        this.system=system;
        this.seller=seller;
        this.sellerOrg = org;
        
        
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png");
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        fileChooser.setFileFilter(jpegFilter);
        txtQuantity.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        btnSelectImage = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 255, 255));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTitle.setText("Title");

        lblImagePath.setText("ImagePath");

        lblPrice.setText("Price");

        lblDescription.setText("Description");

        btnSelectImage.setText("Select Image");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Quantity");

        txtQuantity.setText("1");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImagePath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSelectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagePath)
                    .addComponent(btnSelectImage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addGap(18, 18, 18)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnReset))
                .addGap(474, 474, 474))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSelectImageActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (!validateForm()) {
            return; // Validation failed, stop execution
        }

        try {
            // 1. Collect form data
            String title = txtTitle.getText().trim();
            String description = txtDescription.getText().trim();
            String priceText = txtPrice.getText().trim();
            double price = Double.parseDouble(priceText);
            int quantity = Integer.parseInt(txtQuantity.getText().trim());

            // 2. Generate unique ID
            String listingId = generateListingId();

            // 3. Save image to draft folder
            String imagePath = "";
            if (logoImage != null && imgLogo.getIcon() != null) {
                try {
                    File draftDir = new File("draft_images");
                    if (!draftDir.exists()) {
                        draftDir.mkdirs();
                    }

                    String fileName = seller.getUserId() + "_" + System.currentTimeMillis() + ".jpg";
                    File imageFile = new File(draftDir, fileName);

                    Image image = logoImage.getImage();
                    BufferedImage bufferedImage = new BufferedImage(
                        image.getWidth(null),
                        image.getHeight(null),
                        BufferedImage.TYPE_INT_RGB
                    );

                    Graphics2D g2d = bufferedImage.createGraphics();
                    g2d.drawImage(image, 0, 0, null);
                    g2d.dispose();

                    ImageIO.write(bufferedImage, "jpg", imageFile);

                    imagePath = "draft_images/" + fileName;
                    System.out.println("Image saved to draft: " + imageFile.getAbsolutePath());

                } catch (Exception e) {
                    System.err.println("Error saving draft image: " + e.getMessage());
                    imagePath = "";
                }
            }

            // 4. Create Listing object
            Listing newListing = new Listing(
                listingId,
                seller,
                title,
                description,
                imagePath,
                price
            );
            newListing.setStatus("Pending");
            newListing.setQuantity(quantity);

            // 5. Add to seller's local list
            seller.addListing(newListing);
            system.getListingDirectory().addListing(newListing);
            // 6. Create ListingReviewRequest replace ListingSubmissionRequest
            ListingReviewRequest reviewRequest = new ListingReviewRequest(
                newListing,
                "seller_request_up",                  // Seller applies for listing
                "Seller requests to publish listing"  
            );

            // 7. Submit ContentControlOrganization（Enterprise3）
            boolean requestSubmitted = submitListingReviewToContentControl(reviewRequest);

            if (requestSubmitted) {
                JOptionPane.showMessageDialog(this,
                    "Listing submitted for approval!\n" +
                    "Listing ID: " + listingId + "\n" +
                    "Status: Pending Review\n" +
                    "You can track the status in your listings.\n" +
                    "Note: The listing will be visible only after approval.",
                    "Submission Successful",
                    JOptionPane.INFORMATION_MESSAGE);

                clearForm();

            } else {
                JOptionPane.showMessageDialog(this,
                    "Listing created but failed to submit for approval.\n" +
                    "Please try again or contact administrator.",
                    "Submission Failed",
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Invalid price format or quantity!\nPlease enter valid numbers.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            txtPrice.requestFocus();
            txtPrice.selectAll();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "System error:\n" + e.getMessage() + "\nPlease try again or contact administrator.",
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearForm(); 
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    private boolean validateForm() {
        StringBuilder errors = new StringBuilder();

        // Validate title
        String title = txtTitle.getText().trim();
        if (title.isEmpty()) {
            errors.append("• Product title cannot be empty\n");
        } else if (title.length() < 1) {
            errors.append("• Product title must be at least 1 characters\n");
        } else if (title.length() > 100) {
            errors.append("• Product title cannot exceed 100 characters\n");
        }

        // Validate description
        String description = txtDescription.getText().trim();
        if (description.isEmpty()) {
            errors.append("• Product description cannot be empty\n");
        } else if (description.length() < 1) {
            errors.append("• Product description must be at least 1 characters\n");
        }

        // Validate price
        String priceText = txtPrice.getText().trim();
        if (priceText.isEmpty()) {
            errors.append("• Price cannot be empty\n");
        } else {
            try {
                double price = Double.parseDouble(priceText);
                if (price <= 0) {
                    errors.append("• Price must be greater than 0\n");
                }
            } catch (NumberFormatException e) {
                errors.append("• Price must be a valid number\n");
            }
        }

        // Display errors if any
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                "Please fix the following errors:\n\n" + errors.toString(),
                "Form Validation Failed",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    // Generate unique listing ID
    private String generateListingId() {
        String prefix = "LIST-" + seller.getUserId() + "-";

        List<Listing> existingListings = system.getListingDirectory().getAllListings();

        int maxNumber = 0;      
        for (Listing l : existingListings) {
            if (l.getId().startsWith(prefix)) {
                String[] parts = l.getId().split("-");
                String lastPart = parts[parts.length - 1];

                try {
                    int num = Integer.parseInt(lastPart);
                    if (num > maxNumber) maxNumber = num;
                } catch (NumberFormatException ignore) {}
            }
        }
        int newNumber = maxNumber + 1;
        return prefix + String.format("%04d", newNumber);
    }

    // Clear form method
    private void clearForm() {
        txtTitle.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        

        // Clear image
        logoImage = null;
        if (imgLogo != null) {
            imgLogo.setIcon(null);
            imgLogo.setText("No Image Selected");
        }

        // Set focus back to title
        txtTitle.requestFocus();
    }


    

    

    private void saveTemporaryListing(Listing listing) {
        try {
            File tempDir = new File("temp_listings");
            if (!tempDir.exists()) {
                tempDir.mkdirs();
            }

            File tempFile = new File(tempDir, listing.getId() + ".tmp");
            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(tempFile))) {
                oos.writeObject(listing);
                System.out.println("Temporary listing saved: " + tempFile.getAbsolutePath());
            }
        } catch (Exception e) {
            System.err.println("Failed to save temporary listing: " + e.getMessage());
        }
    }

    private boolean submitListingReviewToContentControl(ListingReviewRequest reviewRequest) {
        System.out.println("=== SUBMIT LISTING REVIEW START ===");

        try {
            // 1. sender
            reviewRequest.setSender(seller);
            System.out.println("Sender set: " + seller.getUsername());

            // 2. Definitely join system-level work directory
            system.getWorkRequestDirectory().addWorkRequest(reviewRequest);
            System.out.println("Added to system work directory");

            // 3. Try it to Content Control
            boolean foundOrg = false;

            for (Network network : system.getNetworks()) {
                for (Enterprise enterprise : network.getEnterprises()) {
                    for (Organization org : enterprise.getOrganizations()) {

                        if ("Content Control".equals(org.getName())) {
                            org.getWorkRequestDirectory().addWorkRequest(reviewRequest);
                            foundOrg = true;
                            System.out.println("Added to Content Control queue");
                        }
                    }
                }
            }

            if (!foundOrg) {
                System.out.println(
                    "WARNING: Content Control not found, but listing review saved to system directory"
                );
            }

            // 4. Submitted successfully
            System.out.println("=== SUBMIT LISTING REVIEW SUCCESS ===");
            return true;

        } catch (Exception e) {
            System.err.println("ERROR submitting listing review: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
            
        
    }
    


}
