/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import basement_class.DAO.ListingDao;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_2.Account.OrderProcessorAccount;
import basement_class.Enterprise_2.Account.SellerAccount;
import basement_class.Enterprise_2.Enterprise.MarketplaceEnterprise;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.ListingDirectory;
import basement_class.Enterprise_2.Organization.SellerOrganization;
import basement_class.Enterprise_2.WorkRequest.ListingSubmissionRequest;
import basement_class.Enterprise_3.WorkRequest.ListingReviewRequest;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.UserAccountDirectory;
import java.awt.Container;
import java.awt.Graphics2D;

import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.ObjectOutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import service.E2.ListingManagementService;



/**
 *
 * @author 心火牧神塞勒斯
 */
public class CreateBulkListingJPanel extends javax.swing.JPanel {

    private SellerAccount sellerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    /**
     * Creates new form CreateNewListingJPanel
     */
    public CreateBulkListingJPanel(EcoSystem system,SellerAccount sellerAccount,Organization organization) {
        initComponents();
        this.sellerAccount = sellerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png");
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        fileChooser.setFileFilter(jpegFilter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        btnSelectImage = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSellerID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTitle.setText("Title");

        lblImagePath.setText("ImagePath");

        lblPrice.setText("Price");

        lblDescription.setText("Description");

        btnSelectImage.setText("Select Image");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Quantity");

        jLabel2.setText("Seller ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImagePath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSelectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSellerID)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectImage)
                    .addComponent(lblImagePath)
                    .addComponent(txtSellerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addGap(18, 18, 18)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnReset))
                .addGap(434, 434, 434))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSelectImageActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (!validateForm()) {
            return;
        }

        try {
            // 1. Collect form data
            String title = txtTitle.getText().trim();
            String description = txtDescription.getText().trim();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int quantity = Integer.parseInt(txtQuantity.getText().trim());
            String sellerId = txtSellerID.getText().trim();

            // 2. Validate seller exists
            UserAccount ua = system.getUserAccountDirectory().findByUserId(sellerId);
            if (!(ua instanceof SellerAccount targetSeller)) {
                JOptionPane.showMessageDialog(this,
                    "Seller ID not found or invalid.",
                    "Invalid Seller",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Generate listing ID
            String listingId = generateListingIdForSeller(sellerId);

            // 4. Save image (draft)
            String imagePath = "";
            if (logoImage != null && imgLogo.getIcon() != null) {
                try {
                    File dir = new File("draft_images");
                    if (!dir.exists()) dir.mkdirs();

                    String fileName = sellerId + "_" + System.currentTimeMillis() + ".jpg";
                    File imageFile = new File(dir, fileName);

                    Image image = logoImage.getImage();
                    BufferedImage bufferedImage = new BufferedImage(
                        image.getWidth(null),
                        image.getHeight(null),
                        BufferedImage.TYPE_INT_RGB
                    );

                    Graphics2D g2d = bufferedImage.createGraphics();
                    g2d.drawImage(image, 0, 0, null);
                    g2d.dispose();

                    ImageIO.write(bufferedImage, "jpg", imageFile);
                    imagePath = "draft_images/" + fileName;

                } catch (Exception e) {
                    System.err.println("Image save error: " + e.getMessage());
                }
            }

            // 5. Create Listing
            Listing newListing = new Listing(
                listingId,
                targetSeller,
                title,
                description,
                imagePath,
                price
            );
            newListing.setQuantity(quantity);
            newListing.setStatus("Pending");

            // 6. Add to seller + system directory
            targetSeller.addListing(newListing);
            system.getListingDirectory().addListing(newListing);

            // ✅ 7. Create ListingReviewRequest
            ListingReviewRequest reviewRequest = new ListingReviewRequest(
                newListing,
                "seller_request_up",
                "Bulk listing created by platform"
            );

            // sender = Currently logged in ListingManager
            reviewRequest.setSender(sellerAccount);

            // Submit to Content Control
            boolean submitted = submitListingReviewToContentControl(reviewRequest);

            if (submitted) {
                JOptionPane.showMessageDialog(this,
                    "Bulk Listing submitted for approval!\n" +
                    "Listing ID: " + listingId,
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Listing created but submission failed.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Invalid price or quantity format.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "System error: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearForm(); 
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellerID;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    private boolean validateForm() {
        StringBuilder errors = new StringBuilder();

        // Validate title
        String title = txtTitle.getText().trim();
        if (title.isEmpty()) {
            errors.append("• Product title cannot be empty\n");
        } else if (title.length() < 1) {
            errors.append("• Product title must be at least 1 characters\n");
        } else if (title.length() > 100) {
            errors.append("• Product title cannot exceed 100 characters\n");
        }

        // Validate description
        String description = txtDescription.getText().trim();
        if (description.isEmpty()) {
            errors.append("• Product description cannot be empty\n");
        } else if (description.length() < 1) {
            errors.append("• Product description must be at least 1 characters\n");
        }

        // Validate price
        String priceText = txtPrice.getText().trim();
        if (priceText.isEmpty()) {
            errors.append("• Price cannot be empty\n");
        } else {
            try {
                double price = Double.parseDouble(priceText);
                if (price <= 0) {
                    errors.append("• Price must be greater than 0\n");
                }
            } catch (NumberFormatException e) {
                errors.append("• Price must be a valid number\n");
            }
        }

        // Display errors if any
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                "Please fix the following errors:\n\n" + errors.toString(),
                "Form Validation Failed",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }



    // Clear form method
    private void clearForm() {
        txtTitle.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtSellerID.setText("");

        // Clear image
        logoImage = null;
        if (imgLogo != null) {
            imgLogo.setIcon(null);
            imgLogo.setText("No Image Selected");
        }

        // Set focus back to title
        txtTitle.requestFocus();
    }


    private String generateListingIdForSeller(String sellerId) {
        String prefix = "LIST-" + sellerId + "-";

        
        List<Listing> existingListings = system.getListingDirectory().getAllListings();

        int maxNumber = 0;
        for (Listing l : existingListings) {
            if (l.getId().startsWith(prefix)) {
                String[] parts = l.getId().split("-");
                String lastPart = parts[parts.length - 1];

                try {
                    int num = Integer.parseInt(lastPart);
                    if (num > maxNumber) maxNumber = num;
                } catch (NumberFormatException ignore) {}
            }
        }

        int newNum = maxNumber + 1;

        return prefix + String.format("%04d", newNum);
    }

    private boolean submitListingReviewToContentControl(ListingReviewRequest reviewRequest) {
        System.out.println("=== SUBMIT BULK LISTING REVIEW ===");

        try {
            // 1. Always add to system directory
            system.getWorkRequestDirectory().addWorkRequest(reviewRequest);
            System.out.println("Added to system work directory");

            // 2. Try to add to Content Control org
            boolean foundOrg = false;

            for (Network network : system.getNetworks()) {
                for (Enterprise enterprise : network.getEnterprises()) {
                    for (Organization org : enterprise.getOrganizations()) {

                        if ("Content Control".equals(org.getName())) {
                            org.getWorkRequestDirectory().addWorkRequest(reviewRequest);
                            foundOrg = true;
                            System.out.println("Added to Content Control queue");
                        }
                    }
                }
            }

            if (!foundOrg) {
                System.out.println(
                    "WARNING: Content Control not found, request still saved system-wide"
                );
            }

            System.out.println("=== SUBMIT LISTING REVIEW SUCCESS ===");
            
            return true;

        } catch (Exception e) {
            System.err.println("ERROR submitting bulk listing review: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    


}
