/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import basement_class.DAO.ListingHelperFunction;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import basement_class.Enterprise_2.Account.SellerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.Organization.SellerOrganization;
import basement_class.Enterprise_3.WorkRequest.PolicyViolationRequest;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import java.io.File;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 心火牧神塞勒斯
 */
public class ManageAllListingJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private SellerAccount seller;
    private SellerOrganization sellerOrg;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    /**
     * Creates new form SellerJPanel
     */
    public ManageAllListingJPanel(EcoSystem system,SellerAccount seller,SellerOrganization org) {
        initComponents();
        this.system=system;
        this.seller=seller;
        this.sellerOrg = org;
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png");
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        fileChooser.setFileFilter(jpegFilter);
        
        loadSellerListings();
        setViewMode();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListing = new javax.swing.JTable();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        btnSelectImage = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblSubmitTime = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtSubmitTime = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblListingID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSellerID = new javax.swing.JTextField();
        btnComplaint = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        tblListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Listing ID", "Price", "Status", "SubmitTime", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblListing);

        lblDescription.setText("Description");

        btnSelectImage.setText("Select Image");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblTitle.setText("Title");

        lblImagePath.setText("ImagePath");

        lblPrice.setText("Price");

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        lblSubmitTime.setText("Submit Time");

        lblListingID.setText("Listing ID");

        jLabel1.setText("Quantity");

        jLabel2.setText("Seller ID ");

        btnComplaint.setText("Start A Complaint");
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus)
                            .addComponent(lblSubmitTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblListingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSelectImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(txtStatus)
                                        .addComponent(txtSubmitTime)
                                        .addComponent(txtID))
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSellerID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(btnComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSellerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescription))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblListingID))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSelectImage)
                                    .addComponent(lblImagePath))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatus)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSubmitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubmitTime)))))
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnComplaint))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSelectImageActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblListing.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a listing from the table first.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. 获取 Listing ID（第 1 列）
            String listingId = (String) tblListing.getValueAt(selectedRow, 1);

            // 2. 从系统查找对应 listing（不再从 seller.getListings() 取）
            Listing selectedListing = system.getListingDirectory().findById(listingId);

            if (selectedListing == null) {
                JOptionPane.showMessageDialog(this,
                    "Selected listing not found in system.",
                    "Listing Not Found",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. 填充 Listing 基本信息
            txtID.setText(selectedListing.getId());
            txtTitle.setText(selectedListing.getTitle());
            txtDescription.setText(selectedListing.getDescription());
            txtPrice.setText(String.format("%.2f", selectedListing.getPrice()));
            txtStatus.setText(selectedListing.getStatus());
            txtQuantity.setText(String.valueOf(selectedListing.getQuantity()));

            // 4. ⭐ 显示 SellerID（新增功能）
            txtSellerID.setText(selectedListing.getSellerId());

            // 5. 显示提交时间
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String submitTime = dateFormat.format(
                Date.from(selectedListing.getSubmitTime()
                        .atZone(ZoneId.systemDefault())
                        .toInstant())
            );
            txtSubmitTime.setText(submitTime);

            // 6. 显示图片
            String imagePath = selectedListing.getImagePath();
            imgLogo.setIcon(null);

            if (imagePath != null && !imagePath.trim().isEmpty()) {
                File imageFile = new File(imagePath);
                if (imageFile.exists()) {
                    ImageIcon listingImage = new ImageIcon(imageFile.getAbsolutePath());
                    if (listingImage.getIconWidth() > 0 && listingImage.getIconHeight() > 0) {

                        int width = imgLogo.getWidth() > 0 ? imgLogo.getWidth() : 150;
                        int height = imgLogo.getHeight() > 0 ? imgLogo.getHeight() : 150;

                        Image scaledImage = listingImage.getImage()
                            .getScaledInstance(width, height, Image.SCALE_SMOOTH);

                        imgLogo.setIcon(new ImageIcon(scaledImage));
                    }
                }
            }

            // 7. 调试输出
            System.out.println("Viewing listing: " + selectedListing.getId()
                + " | seller = " + selectedListing.getSellerId());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error loading listing details: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblListing.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a listing to save changes.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. Get listing ID from table
            String listingId = (String) tblListing.getValueAt(selectedRow, 1);

            
            Listing selectedListing = system.getListingDirectory().findById(listingId);

            if (selectedListing == null) {
                JOptionPane.showMessageDialog(this,
                    "Listing not found in system.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Read updated values from text fields
            String newTitle = txtTitle.getText().trim();
            String newDescription = txtDescription.getText().trim();
            double newPrice = Double.parseDouble(txtPrice.getText().trim());
            int newQuantity = Integer.parseInt(txtQuantity.getText().trim());

            // 4. Update Listing object
            selectedListing.setTitle(newTitle);
            selectedListing.setDescription(newDescription);
            selectedListing.setPrice(newPrice);
            selectedListing.setQuantity(newQuantity);

            // 5. Update submit time
            selectedListing.setSubmitTime(LocalDateTime.now());

            // 6. Update table
            DefaultTableModel model = (DefaultTableModel) tblListing.getModel();
            model.setValueAt(newTitle, selectedRow, 0);
            model.setValueAt(String.format("$%.2f", newPrice), selectedRow, 2);
            model.setValueAt(selectedListing.getStatus(), selectedRow, 3);

            String updatedTime = new SimpleDateFormat("yyyy-MM-dd HH:mm")
                    .format(Date.from(selectedListing.getSubmitTime()
                            .atZone(ZoneId.systemDefault())
                            .toInstant()));

            model.setValueAt(updatedTime, selectedRow, 4);
            model.setValueAt(newQuantity, selectedRow, 5);

            JOptionPane.showMessageDialog(this,
                "Listing updated successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Invalid number format in Price or Quantity.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error saving changes: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }

        clearForm();
        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setUpdateMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
        System.out.println("=== COMPLAINT PROCESS START ===");
    
        int selectedRow = tblListing.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("ERROR: No row selected");
            JOptionPane.showMessageDialog(this,
                "Please select a listing first.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.out.println("Step 1: Row selected: " + selectedRow);

        // 1. Get listing ID from table
        String listingId = (String) tblListing.getValueAt(selectedRow, 1);
        System.out.println("Step 2: Listing ID from table: " + listingId);

        // 2. Get the listing object from global directory
        Listing selectedListing = system.getListingDirectory().findById(listingId);

        if (selectedListing == null) {
            System.out.println("ERROR: Listing not found in system directory");
            JOptionPane.showMessageDialog(this,
                "Listing not found in system.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        System.out.println("Step 3: Listing found: " + selectedListing.getTitle());

        // 3. Get seller account from system
        String sellerId = selectedListing.getSellerId();
        System.out.println("Step 4: Seller ID from listing: " + sellerId);

        UserAccount targetSeller = system.getUserAccountDirectory().findByUserId(sellerId);

        if (targetSeller == null) {
            System.out.println("ERROR: Cannot find seller account for ID: " + sellerId);
            JOptionPane.showMessageDialog(this,
                "Cannot find seller account for this listing.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        System.out.println("Step 5: Target seller found: " + targetSeller.getUsername());

        // 4. Ask for complaint reason
        String reason = JOptionPane.showInputDialog(
                this,
                "Enter complaint reason:",
                "Complaint",
                JOptionPane.PLAIN_MESSAGE
        );

        if (reason == null) {
            System.out.println("INFO: User cancelled complaint (clicked Cancel)");
            return;
        }

        if (reason.trim().isEmpty()) {
            System.out.println("INFO: User provided empty reason");
            JOptionPane.showMessageDialog(this,
                "Complaint cancelled (no reason provided).",
                "Cancelled",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.out.println("Step 6: Reason provided: " + reason);

        // 5. Create the PolicyViolationRequest
        System.out.println("Step 7: Creating PolicyViolationRequest...");
        System.out.println("  Reporter: " + seller.getUsername());
        System.out.println("  Target: " + targetSeller.getUsername());
        System.out.println("  Listing: " + selectedListing.getId());

        try {
            PolicyViolationRequest request = new PolicyViolationRequest(
                seller,                     // reporter
                targetSeller,               // target user
                selectedListing,            // listing
                "listing_issue",            // category
                reason                      // info
            );

            System.out.println("Step 8: Request created successfully");
            System.out.println("  Request ID: " + request.getId());
            System.out.println("  Request listing: " + (request.getListing() != null ? request.getListing().getId() : "NULL"));

            // 6. Submit to Policy Management Organization
            System.out.println("Step 9: Submitting complaint...");
            boolean sent = submitComplaintToPolicyManagement(request);

            if (sent) {
                System.out.println("SUCCESS: Complaint submitted!");
                JOptionPane.showMessageDialog(this,
                    "Complaint submitted successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("FAILED: submitComplaintToPolicyManagement returned false");
                JOptionPane.showMessageDialog(this,
                    "Failed to submit complaint.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            System.err.println("ERROR: Exception creating request: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error creating complaint: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }

        System.out.println("=== COMPLAINT PROCESS END ===");
    }//GEN-LAST:event_btnComplaintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblListingID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubmitTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblListing;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellerID;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSubmitTime;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables



    private void loadSellerListings() {
        // 1. 获取当前卖家的所有Listing
        List<Listing> allListings = system.getListingDirectory().getAllListings();

        // 2. 获取表格模型
        DefaultTableModel model = (DefaultTableModel) tblListing.getModel();

        // 3. 清空表格现有数据
        model.setRowCount(0);

        // 4. 添加数据到表格
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");

        for (Listing listing : allListings) {
            Object[] rowData = new Object[6];

            rowData[0] = listing.getTitle();                // Title
            rowData[1] = listing.getId();                   // ID
            rowData[2] = String.format("$%.2f", listing.getPrice()); // Price
            rowData[3] = listing.getStatus();               // Status
            rowData[4] = dateFormat.format(Date.from(listing.getSubmitTime().atZone(ZoneId.systemDefault()).toInstant())); // Submit Date
            rowData[5] = listing.getQuantity();   
            model.addRow(rowData);
        }

        // 5. 更新表格显示
        tblListing.revalidate();
        tblListing.repaint();

        // 6. 显示记录数
        System.out.println("Loaded " + allListings.size() + " listings for seller: " + seller.getUsername());
    }

    private void clearForm() {
        txtTitle.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");

        // Clear image
        logoImage = null;
        if (imgLogo != null) {
            imgLogo.setIcon(null);
            imgLogo.setText("No Image Selected");
        }

        // Set focus back to title
        txtTitle.requestFocus();
    }

    private void setViewMode() {
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtDescription.setEnabled(false);
        txtID.setEnabled(false);
        txtPrice.setEnabled(false);
        txtQuantity.setEnabled(false);
        txtStatus.setEnabled(false);
        txtSubmitTime.setEnabled(false);
        txtTitle.setEnabled(false);
        btnSelectImage.setEnabled(false);
    }

    private void setUpdateMode() {
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtDescription.setEnabled(true);
        txtID.setEnabled(true);
        txtPrice.setEnabled(true);
        txtQuantity.setEnabled(true);
        txtStatus.setEnabled(false);
        txtSubmitTime.setEnabled(true);
        txtTitle.setEnabled(true);
        btnSelectImage.setEnabled(true);
    }

    private boolean submitComplaintToPolicyManagement(PolicyViolationRequest request) {
        System.out.println("Step 9.1: Starting submission...");
    
        try {
            // Set sender
            request.setSender(seller);
            System.out.println("Step 9.2: Sender set to: " + seller.getUsername());

            // 方案A: 尝试添加到系统目录
            System.out.println("Step 9.3: Trying to add to system work directory...");
            system.getWorkRequestDirectory().addWorkRequest(request);
            System.out.println("Step 9.4: Added to system directory");

            // 方案B: 尝试找到Content Control组织
            System.out.println("Step 9.5: Looking for Content Control organization...");
            boolean foundOrg = false;

            for (Network network : system.getNetworks()) {
                System.out.println("  Network: " + network.getName());

                for (Enterprise enterprise : network.getEnterprises()) {
                    System.out.println("    Enterprise: " + enterprise.getName());

                    for (Organization org : enterprise.getOrganizations()) {
                        System.out.println("      Organization: " + org.getName());

                        if (org.getName().equals("Content Control")) {
                            System.out.println("      FOUND Content Control!");
                            org.getWorkRequestDirectory().addWorkRequest(request);
                            foundOrg = true;
                            System.out.println("      Added to organization queue");
                        }
                    }
                }
            }

            if (!foundOrg) {
                System.out.println("WARNING: Content Control organization not found, but complaint saved to system directory");
            }

            // 方案C: 保存到文件
            System.out.println("Step 9.6: Saving complaint to file...");
            saveComplaintToFile(request);

            System.out.println("Step 9.7: All submission methods completed");
            return true;

        } catch (Exception e) {
            System.err.println("ERROR in submission: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    private void saveComplaintToFile(PolicyViolationRequest request) {
        try {
            File dir = new File("data/complaints");
            if (!dir.exists()) {
                dir.mkdirs();
            }

            String filename = "complaint_" + request.getId() + "_" + System.currentTimeMillis() + ".txt";
            File file = new File(dir, filename);

            try (PrintWriter pw = new PrintWriter(file)) {
                pw.println("=== COMPLAINT REPORT ===");
                pw.println("ID: " + request.getId());
                pw.println("Date: " + new Date());
                pw.println("Reporter: " + request.getReporter().getUsername());
                pw.println("Target: " + request.getTargetUser().getUsername());
                pw.println("Listing ID: " + request.getListing().getId());
                pw.println("Listing Title: " + request.getListing().getTitle());
                pw.println("Category: " + request.getViolationCategory());
                pw.println("Reason: " + request.getViolationInfo());
                pw.println("Status: " + request.getStatus());
            }

            System.out.println("Complaint saved to file: " + file.getAbsolutePath());

        } catch (Exception e) {
            System.err.println("WARNING: Could not save to file: " + e.getMessage());
        }
    }
    

    
}
