/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import UI.Enterprise4.BuyerSellerChatPanel;
//import basement_class.DAO.ListingDao;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import basement_class.Enterprise_2.Account.SellerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.Organization.SellerOrganization;
import basement_class.Enterprise_4.CommunicationServiceOrganization;
import basement_class.Enterprise_4.MessageDirectory;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import common_class.Order;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author 心火牧神塞勒斯
 */
public class ManageListingJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private SellerAccount seller;
    private SellerOrganization sellerOrg;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    /**
     * Creates new form SellerJPanel
     */
    public ManageListingJPanel(EcoSystem system,SellerAccount seller,SellerOrganization org) {
        initComponents();
        this.system=system;
        this.seller=seller;
        this.sellerOrg = org;
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png");
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        fileChooser.setFileFilter(jpegFilter);
        
        loadSellerListings();
        setViewMode();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListing = new javax.swing.JTable();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        btnSelectImage = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblSubmitTime = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtSubmitTime = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblListingID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnTalkWithUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 255));

        tblListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Listing ID", "Price", "Status", "SubmitTime", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblListing);

        lblDescription.setText("Description");

        btnSelectImage.setText("Select Image");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblTitle.setText("Title");

        lblImagePath.setText("ImagePath");

        lblPrice.setText("Price");

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        lblSubmitTime.setText("Submit Time");

        lblListingID.setText("Listing ID");

        jLabel1.setText("Quantity");

        btnTalkWithUser.setText("Talk with Buyer");
        btnTalkWithUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTalkWithUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus)
                            .addComponent(lblSubmitTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblListingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnSelectImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(txtStatus)
                                            .addComponent(txtSubmitTime)
                                            .addComponent(txtID))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(lblDescription))
                                            .addComponent(btnTalkWithUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnTalkWithUser))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescription))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblListingID))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSelectImage)
                                    .addComponent(lblImagePath))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatus)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSubmitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubmitTime)))))
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSelectImageActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblListing.getSelectedRow();

        // 2. 检查是否有选中的行
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a listing from the table first.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 3. 从选中的行获取 Listing ID
            String listingId = (String) tblListing.getValueAt(selectedRow, 1); // 第二列是ID

            // 4. 根据ID查找Listing对象
            Listing selectedListing = null;
            for (Listing listing : seller.getListings()) {
                if (listing.getId().equals(listingId)) {
                    selectedListing = listing;
                    break;
                }
            }

            if (selectedListing == null) {
                JOptionPane.showMessageDialog(this,
                    "Selected listing not found in seller's list.",
                    "Listing Not Found",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 5. 将Listing信息填充到文本框中
            txtID.setText(selectedListing.getId());
            txtTitle.setText(selectedListing.getTitle());
            txtDescription.setText(selectedListing.getDescription());
            txtPrice.setText(String.format("%.2f", selectedListing.getPrice()));
            txtStatus.setText(selectedListing.getStatus());
            txtQuantity.setText(String.valueOf(selectedListing.getQuantity()));

            // 格式化提交时间
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String submitTime = dateFormat.format(
                Date.from(selectedListing.getSubmitTime().atZone(ZoneId.systemDefault()).toInstant())
            );
            txtSubmitTime.setText(submitTime);

            // 6. 显示图片
            String imagePath = selectedListing.getImagePath();
            System.out.println("Loading image from path: " + imagePath);

            // 清除之前的显示
            imgLogo.setIcon(null);

            if (imagePath != null && !imagePath.trim().isEmpty()) {
                try {
                    File imageFile = new File(imagePath);

                    // 调试信息
                    System.out.println("Image file absolute path: " + imageFile.getAbsolutePath());
                    System.out.println("Image file exists: " + imageFile.exists());

                    if (imageFile.exists()) {
                        // 加载图片
                        ImageIcon listingImage = new ImageIcon(imageFile.getAbsolutePath());

                        // 检查图片是否有效加载
                        if (listingImage.getIconWidth() > 0 && listingImage.getIconHeight() > 0) {
                            // 调整大小以适应显示区域
                            int width = imgLogo.getWidth() > 0 ? imgLogo.getWidth() : 150;
                            int height = imgLogo.getHeight() > 0 ? imgLogo.getHeight() : 150;

                            Image scaledImage = listingImage.getImage().getScaledInstance(
                                width, height, Image.SCALE_SMOOTH);

                            imgLogo.setIcon(new ImageIcon(scaledImage));
                            System.out.println("Image loaded and displayed successfully");
                        } else {
                            System.out.println("Image loaded but has zero dimensions");
                        }
                    } else {
                        System.out.println("Image file does not exist: " + imageFile.getAbsolutePath());
                    }

                } catch (Exception e) {
                    System.err.println("Error loading image: " + e.getMessage());
                }
            } else {
                System.out.println("No image path specified for this listing");
            }

            // 7.在控制台输出调试信息
            System.out.println("Viewing listing: " + selectedListing.getId() + " - " + selectedListing.getTitle());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error loading listing details: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblListing.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a listing to save changes.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. Get listing ID from table
            String listingId = (String) tblListing.getValueAt(selectedRow, 1);

            // 2. Find listing object from seller
            Listing selectedListing = null;
            for (Listing listing : seller.getListings()) {
                if (listing.getId().equals(listingId)) {
                    selectedListing = listing;
                    break;
                }
            }

            if (selectedListing == null) {
                JOptionPane.showMessageDialog(this,
                    "Listing not found.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Read updated values from text fields
            String newTitle = txtTitle.getText().trim();
            String newDescription = txtDescription.getText().trim();
            double newPrice = Double.parseDouble(txtPrice.getText().trim());
            int newQuantity = Integer.parseInt(txtQuantity.getText().trim());

            // 4. Update Listing object
            selectedListing.setTitle(newTitle);
            selectedListing.setDescription(newDescription);
            selectedListing.setPrice(newPrice);
            selectedListing.setQuantity(newQuantity);

            // 5. Update submit time to "now" (optional but realistic)
            selectedListing.setSubmitTime(LocalDateTime.now());

            // 6. Update table row to reflect changes
            DefaultTableModel model = (DefaultTableModel) tblListing.getModel();
            model.setValueAt(newTitle, selectedRow, 0);
            model.setValueAt(String.format("$%.2f", newPrice), selectedRow, 2);
            model.setValueAt(selectedListing.getStatus(), selectedRow, 3);

            String updatedTime = new SimpleDateFormat("yyyy-MM-dd HH:mm")
                    .format(Date.from(selectedListing.getSubmitTime()
                            .atZone(ZoneId.systemDefault())
                            .toInstant()));

            model.setValueAt(updatedTime, selectedRow, 4);
            model.setValueAt(newQuantity, selectedRow, 5);  // Quantity column

            // 7. Notify user
            JOptionPane.showMessageDialog(this,
                "Listing updated successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Invalid number format in Price or Quantity.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error saving changes: " + e.getMessage(),
                "System Error",
                JOptionPane.ERROR_MESSAGE);
        }
        clearForm(); 
        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setUpdateMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTalkWithUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTalkWithUserActionPerformed
        // Start a chat with the seller of this listing

        // Basic checks
        int row = tblListing.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a listing first.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ✅ 1. 通过表格获取 Listing ID
        String listingId = (String) tblListing.getValueAt(row, 1);

        Listing listing = system.getListingDirectory().findById(listingId);
        if (listing == null) {
            JOptionPane.showMessageDialog(this,
                    "Listing not found.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ 2. 必须是 Reserved 才允许聊天
        if (!"Reserved".equalsIgnoreCase(listing.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "This listing has not been reserved by any buyer.",
                    "No Active Order",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // ✅ 3. 通过 ListingID 找到当前有效 Order
        Order order = system.getOrderDirectory()
                .findActiveOrderByListingId(listing.getId());

        if (order == null) {
            JOptionPane.showMessageDialog(this,
                    "No active order found for this listing.",
                    "Order Not Found",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ 4. 找 Buyer
        UserAccount buyer =
                system.getUserAccountDirectory().findByUserId(order.getBuyerId());

        if (buyer == null) {
            JOptionPane.showMessageDialog(this,
                    "Buyer account not found.",
                    "User Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ 5. 封装对话对象（Buyer）
        ArrayList<UserAccount> partners = new ArrayList<>();
        partners.add(buyer);

        // ✅ 6. 获取全局 MessageDirectory
        MessageDirectory messageDirectory = system.getMessageDirectory();

        // ✅ 7. 查找 CommunicationServiceOrganization
        CommunicationServiceOrganization commOrg = null;
        for (Network n : system.getNetworks()) {
            for (Enterprise e : n.getEnterprises()) {
                for (Organization org : e.getOrganizations()) {
                    if (org instanceof CommunicationServiceOrganization) {
                        commOrg = (CommunicationServiceOrganization) org;
                        break;
                    }
                }
            }
        }

        if (commOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "CommunicationServiceOrganization not found.",
                    "System Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ 8. 创建 Chat Panel（Seller → Buyer）
        BuyerSellerChatPanel chatPanel = new BuyerSellerChatPanel(
                seller,     // 当前用户：Seller
                partners,          // 对话对象：Buyer
                messageDirectory,
                commOrg
        );

        // ✅ 9. 切换到 Chat Panel（无 CardLayout 版本）
        JPanel workPanel = findWorkProcessPanel(this);
        if (workPanel == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot locate work area panel.",
                    "UI Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        workPanel.removeAll();
        workPanel.setLayout(new BorderLayout());
        workPanel.add(chatPanel, BorderLayout.CENTER);
        workPanel.revalidate();
        workPanel.repaint();
    }//GEN-LAST:event_btnTalkWithUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JButton btnTalkWithUser;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblListingID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubmitTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblListing;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSubmitTime;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables



    private void loadSellerListings() {
        // 1. 获取当前卖家的所有Listing
        List<Listing> sellerListings = seller.getListings();

        // 2. 获取表格模型
        DefaultTableModel model = (DefaultTableModel) tblListing.getModel();

        // 3. 清空表格现有数据
        model.setRowCount(0);

        // 4. 添加数据到表格
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");

        for (Listing listing : sellerListings) {
            Object[] rowData = new Object[6];

            rowData[0] = listing.getTitle();                // Title
            rowData[1] = listing.getId();                   // ID
            rowData[2] = String.format("$%.2f", listing.getPrice()); // Price
            rowData[3] = listing.getStatus();               // Status
            rowData[4] = dateFormat.format(Date.from(listing.getSubmitTime().atZone(ZoneId.systemDefault()).toInstant())); // Submit Date
            rowData[5] = listing.getQuantity();   
            model.addRow(rowData);
        }

        // 5. 更新表格显示
        tblListing.revalidate();
        tblListing.repaint();

        // 6. 显示记录数
        System.out.println("Loaded " + sellerListings.size() + " listings for seller: " + seller.getUsername());
    }

    private void clearForm() {
        txtTitle.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");

        // Clear image
        logoImage = null;
        if (imgLogo != null) {
            imgLogo.setIcon(null);
            imgLogo.setText("No Image Selected");
        }

        // Set focus back to title
        txtTitle.requestFocus();
    }

    private void setViewMode() {
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtDescription.setEnabled(false);
        txtID.setEnabled(false);
        txtPrice.setEnabled(false);
        txtQuantity.setEnabled(false);
        txtStatus.setEnabled(false);
        txtSubmitTime.setEnabled(false);
        txtTitle.setEnabled(false);
        btnSelectImage.setEnabled(false);
    }

    private void setUpdateMode() {
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtDescription.setEnabled(true);
        txtID.setEnabled(true);
        txtPrice.setEnabled(true);
        txtQuantity.setEnabled(true);
        txtStatus.setEnabled(false);
        txtSubmitTime.setEnabled(true);
        txtTitle.setEnabled(true);
        btnSelectImage.setEnabled(true);
    }
    
    private CommunicationServiceOrganization findCommunicationServiceOrg(EcoSystem system) {

        if (system == null) {
            return null;
        }

        // Search through all networks → enterprises → organizations
        for (Network net : system.getNetworks()) {
            for (Enterprise ent : net.getEnterprises()) {

                // Loop through organizations inside this enterprise
                for (Organization org : ent.getOrganizations()) {

                    // Check if this org is the communication service org
                    if (org instanceof CommunicationServiceOrganization) {
                        return (CommunicationServiceOrganization) org;
                    }
                }
            }
        }

        // Not found
        return null;
    }
        private JPanel findWorkProcessPanel(Component comp) {
        while (comp != null) {
            if (comp instanceof JPanel panel
                    && "workProcessJPanel".equals(panel.getName())) {
                return panel;
            }
            comp = comp.getParent();
        }
        return null;
    }
    

    
}
