/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import UI.main.LoginPage;
import basement_class.DAO.ListingFileDAO;
import basement_class.DAO.ListingService;
import basement_class.DAO.OdedrService;
import basement_class.DAO.OderFileDAO;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_2.Account.OrderProcessorAccount;
import basement_class.Organization;
import common_class.Order;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class OrderProcessorJPanel extends javax.swing.JPanel {
    private OrderProcessorAccount orderProcessorAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form SellerJPanel
     * @param orderProcessorAccount
     * @param organization
     * @param enterprise
     * @param system
     */
    public OrderProcessorJPanel(OrderProcessorAccount orderProcessorAccount,Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.orderProcessorAccount = orderProcessorAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnOrderReports = new javax.swing.JButton();
        btnReviewOrders = new javax.swing.JButton();
        workProcessJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(255, 204, 204));
        controlJPanel.setForeground(new java.awt.Color(102, 255, 255));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        btnOrderReports.setText("Order Reports");
        btnOrderReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderReportsActionPerformed(evt);
            }
        });

        btnReviewOrders.setText("Review Orders");
        btnReviewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrderReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnReviewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnReviewOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderHistory)
                .addGap(18, 18, 18)
                .addComponent(btnOrderReports)
                .addGap(38, 38, 38)
                .addComponent(btnLogout)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlJPanel);

        javax.swing.GroupLayout workProcessJPanelLayout = new javax.swing.GroupLayout(workProcessJPanel);
        workProcessJPanel.setLayout(workProcessJPanelLayout);
        workProcessJPanelLayout.setHorizontalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        workProcessJPanelLayout.setVerticalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workProcessJPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        OrderHistoryJPanel panel =
        new OrderHistoryJPanel(orderProcessorAccount, organization, enterprise, system);

        replaceWorkArea(panel);
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void btnOrderReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderReportsActionPerformed
        // TODO add your handling code here:
        List<Order> allOrders = system.getOrderDirectory().getAllOrders();

        if (allOrders == null || allOrders.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No orders found in the system.",
                    "Order Report",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int total = allOrders.size();

        int pending = 0;
        int accepted = 0;
        int rejected = 0;
        int completed = 0;
        int cancelled = 0;

        // ✅ Count statuses
        for (Order order : allOrders) {
            switch (order.getStatus()) {
                case Order.STATUS_PENDING -> pending++;
                case Order.STATUS_ACCEPTED -> accepted++;
                case Order.STATUS_REJECTED -> rejected++;
                case Order.STATUS_COMPLETED -> completed++;
                case Order.STATUS_CANCELLED -> cancelled++;
            }
        }

        // ✅ Percentage helper
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");

        String report =
                "===== ORDER REPORT =====\n\n" +
                "Total Orders: " + total + "\n\n" +

                "PENDING: " + pending +
                " (" + df.format(pending * 100.0 / total) + "%)\n" +

                "ACCEPTED: " + accepted +
                " (" + df.format(accepted * 100.0 / total) + "%)\n" +

                "REJECTED: " + rejected +
                " (" + df.format(rejected * 100.0 / total) + "%)\n" +

                "COMPLETED: " + completed +
                " (" + df.format(completed * 100.0 / total) + "%)\n" +

                "CANCELLED: " + cancelled +
                " (" + df.format(cancelled * 100.0 / total) + "%)\n\n" +

                "========================";

        JOptionPane.showMessageDialog(this,
                report,
                "Order Report Summary",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnOrderReportsActionPerformed

    private void btnReviewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOrdersActionPerformed
        // TODO add your handling code here:
        ReviewOrdersJPanel panel =
        new ReviewOrdersJPanel(orderProcessorAccount, organization, enterprise, system);

        replaceWorkArea(panel);
    }//GEN-LAST:event_btnReviewOrdersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        mainFrame.dispose();

        LoginPage loginPage = new LoginPage(system);  // ✅ 核心就在这一句！
        loginPage.setVisible(true);
            new OdedrService(
        new OderFileDAO(),
        system.getOrderDirectory()
    ).saveOrders();

    new ListingService(
        new ListingFileDAO(),
        system.getListingDirectory()
    ).saveListings();

    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnOrderReports;
    private javax.swing.JButton btnReviewOrders;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workProcessJPanel;
    // End of variables declaration//GEN-END:variables

    private void replaceWorkArea(JPanel panel) {
        workProcessJPanel.removeAll();
        workProcessJPanel.setLayout(new BorderLayout());
        workProcessJPanel.add(panel, BorderLayout.CENTER);

        // 强制重新验证和重绘
        workProcessJPanel.revalidate();
        workProcessJPanel.repaint();

        // 确保父容器也更新
        workProcessJPanel.getParent().revalidate();
        workProcessJPanel.getParent().repaint();
    } 
}
