/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise2;

import UI.Enterprise4.BuyerSellerChatPanel;
import UI.main.LoginPage;
import basement_class.DAO.ListingFileDAO;
import basement_class.DAO.ListingService;
import basement_class.DAO.OdedrService;
import basement_class.DAO.OderFileDAO;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_2.Account.SellerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.Organization.SellerOrganization;
import basement_class.Enterprise_4.CommunicationServiceOrganization;
import basement_class.Enterprise_4.MessageDirectory;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import common_class.Order;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class SellerJPanel extends javax.swing.JPanel {
    private SellerAccount sellerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Order order;
    /**
     * Creates new form SellerJPanel
     * @param sellerAccount
     * @param organization
     * @param enterprise
     * @param system
     */
    public SellerJPanel(SellerAccount sellerAccount,Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.sellerAccount = sellerAccount;
        this.order = order;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        workProcessJPanel.setName("workProcessJPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnListingMangement = new javax.swing.JButton();
        btnCreateNewListing = new javax.swing.JButton();
        workProcessJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(102, 255, 255));
        controlJPanel.setForeground(new java.awt.Color(102, 255, 255));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnListingMangement.setText("Listing  Management");
        btnListingMangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListingMangementActionPerformed(evt);
            }
        });

        btnCreateNewListing.setText("Create New Listing");
        btnCreateNewListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewListingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListingMangement, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnCreateNewListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCreateNewListing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListingMangement)
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlJPanel);

        javax.swing.GroupLayout workProcessJPanelLayout = new javax.swing.GroupLayout(workProcessJPanel);
        workProcessJPanel.setLayout(workProcessJPanelLayout);
        workProcessJPanelLayout.setHorizontalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        workProcessJPanelLayout.setVerticalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workProcessJPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListingMangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListingMangementActionPerformed
        ManageListingJPanel panel =
        new ManageListingJPanel(workProcessJPanel, system, sellerAccount, (SellerOrganization) organization);
        replaceWorkArea(panel);
    }//GEN-LAST:event_btnListingMangementActionPerformed

    private void btnCreateNewListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewListingActionPerformed
        // TODO add your handling code here:
        CreateNewListingJPanel panel =
        new CreateNewListingJPanel(system, sellerAccount, (SellerOrganization) organization);

        replaceWorkArea(panel);
    }//GEN-LAST:event_btnCreateNewListingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // ✅ 2️⃣ 销毁旧窗口（只销毁 UI）
        mainFrame.dispose();

        // ✅ 3️⃣ 用【同一个 system】重新打开 Login
        LoginPage loginPage = new LoginPage(system);  // ✅ 核心就在这一句！
        loginPage.setVisible(true);
<<<<<<< Updated upstream
                OdedrService orderService = new OdedrService(
                new OderFileDAO(),
                system.getOrderDirectory()
        );
        orderService.saveOrders();
        
          new ListingService(
            new ListingFileDAO(),
            system.getListingDirectory()
        ).saveListings();
=======
            new OdedrService(
        new OderFileDAO(),
        system.getOrderDirectory()
    ).saveOrders();

    new ListingService(
        new ListingFileDAO(),
        system.getListingDirectory()
    ).saveListings();

>>>>>>> Stashed changes
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewListing;
    private javax.swing.JButton btnListingMangement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workProcessJPanel;
    // End of variables declaration//GEN-END:variables

    private void replaceWorkArea(JPanel panel) {
        workProcessJPanel.removeAll();
        workProcessJPanel.setLayout(new BorderLayout());
        workProcessJPanel.add(panel, BorderLayout.CENTER);

        // 强制重新验证和重绘
        workProcessJPanel.revalidate();
        workProcessJPanel.repaint();

        // 确保父容器也更新
        workProcessJPanel.getParent().revalidate();
        workProcessJPanel.getParent().repaint();
    }
    public void showChatPanel(JPanel chatPanel) {
        replaceWorkArea(chatPanel);
    }
    
}
