/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.ListingDirectory;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bob-h
 */
public class BrowseWorkArea extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private EcoSystem system;
    private BuyerJPanel parentPanel;  // Reference to parent
    /**
     * Creates new form BrowseWorkArea
     */
    public BrowseWorkArea(BuyerAccount buyerAccount, EcoSystem system, BuyerJPanel parent) {
        initComponents();
        this.buyerAccount = buyerAccount;
        this.system = system;
        this.parentPanel = parent;
        
        initComponents();
        
        // Load listings on creation
        refreshListings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListing = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        tblListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Listing ID", "Name", "Category", "Price", "Condition", "Status", "Seller"
            }
        ));
        jScrollPane1.setViewportView(tblListing);

        btnCheck.setText("Check out");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnDetail.setText("Detailed");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                        .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail)
                    .addComponent(btnAdd))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListing;
    // End of variables declaration//GEN-END:variables

    public void refreshListings() {
        ListingDirectory listingDir = system.getListingDirectory();
        List<Listing> listings = listingDir.findByStatus("Approved");
        
        DefaultTableModel model = (DefaultTableModel) tblListing.getModel();
        model.setRowCount(0);
        
        for (Listing listing : listings) {
            Object[] row = {
                listing.getId(),
                listing.getTitle(),
                "Unknown",  // Category - if Listing doesn't have category
                listing.getPrice(),
                "Unknown",  // Condition - if Listing doesn't have condition
                listing.getStatus(),
                listing.getSeller().getUsername()
            };
            model.addRow(row);
        }
    }
    
    public Listing getSelectedListing() {
        int selectedRow = tblListing.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        }
        
        String listingId = (String) tblListing.getValueAt(selectedRow, 0);
        return system.getListingDirectory().findById(listingId);
    }
    
}
