/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.ListingDirectory;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bob-h
 */
public class BrowseWorkArea extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private EcoSystem system;
    private BuyerJPanel parentPanel;
    /**
     * Creates new form BrowseWorkArea
     */
    public BrowseWorkArea(BuyerAccount buyerAccount, EcoSystem system, BuyerJPanel parent) {
        this.buyerAccount = buyerAccount;
        this.system = system;
        this.parentPanel = parent;
        
        initComponents();
        
        // Add listener for combo box
        cmbCategoryForListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryForListingActionPerformed(evt);
            }
        });
        
        // Add listener for detail button
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        
        // Load listings on creation
        refreshListings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListing = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        cmbCategoryForListing = new javax.swing.JComboBox<>();

        tblListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Listing ID", "Name", "Price", "Status", "Seller"
            }
        ));
        jScrollPane1.setViewportView(tblListing);

        btnCheck.setText("Check out");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnDetail.setText("Detailed");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbCategoryForListing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Favorites" }));
        cmbCategoryForListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryForListingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCategoryForListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(cmbCategoryForListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // Add selected listing to cart
        if (parentPanel != null) {
            parentPanel.showShoppingCart();
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Listing selected = getSelectedListing();
        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a product first",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if it's user's own listing
        if (selected.getSeller().getUserId().equals(buyerAccount.getUserId())) {
            JOptionPane.showMessageDialog(this,
                "Cannot add your own product to cart",
                "Invalid Operation",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if listing is available
        if (!"Approved".equals(selected.getStatus())) {
            JOptionPane.showMessageDialog(this,
                "This product is not available for purchase",
                "Unavailable",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Add to cart through parent panel
        parentPanel.addToCart(selected);
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbCategoryForListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryForListingActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbCategoryForListing.getSelectedIndex();
        if (selectedIndex == 0) {
            // Normal view - show all products
            refreshListings();
        } else if (selectedIndex == 1) {
            // Favorites view
            showFavorites();
        }
    }//GEN-LAST:event_cmbCategoryForListingActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        // Show detailed view
        Listing selected = getSelectedListing();
        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a product first",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Create and show detail panel
        ListingDetailWorkArea detailPanel = new ListingDetailWorkArea(
            selected, buyerAccount, system, parentPanel
        );
        
        // Add to parent's card layout and show
        parentPanel.showDetailPanel(detailPanel);
    }//GEN-LAST:event_btnDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDetail;
    private javax.swing.JComboBox<String> cmbCategoryForListing;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListing;
    // End of variables declaration//GEN-END:variables

    /**
     * Refresh all approved listings
     */
    public void refreshListings() {
        ListingDirectory listingDir = system.getListingDirectory();
        List<Listing> listings = listingDir.findByStatus("Approved");
        
        displayListings(listings);
    }
    
    /**
     * Show only favorite listings
     */
    private void showFavorites() {
        ListingDirectory listingDir = system.getListingDirectory();
        List<String> favoriteIds = buyerAccount.getFavoriteListingIds();
        
        DefaultTableModel model = (DefaultTableModel) tblListing.getModel();
        model.setRowCount(0);
        
        for (String listingId : favoriteIds) {
            Listing listing = listingDir.findById(listingId);
            if (listing != null && "Approved".equals(listing.getStatus())) {
                addListingToTable(listing, model);
            }
        }
    }
    
    /**
     * Display a list of listings in the table
     */
    private void displayListings(List<Listing> listings) {
        DefaultTableModel model = (DefaultTableModel) tblListing.getModel();
        model.setRowCount(0);
        
        for (Listing listing : listings) {
            addListingToTable(listing, model);
        }
    }
    
    /**
     * Add a single listing to the table
     */
    private void addListingToTable(Listing listing, DefaultTableModel model) {
        Object[] row = {
            listing.getId(),                           // Listing ID
            listing.getTitle(),                        // Title
            String.format("$%.2f", listing.getPrice()), // Price
            listing.getStatus(),                       // Status
            listing.getSeller().getUsername()          // Seller
        };
        model.addRow(row);
    }
    
    /**
     * Get the currently selected listing
     */
    public Listing getSelectedListing() {
        int selectedRow = tblListing.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        }
        
        String listingId = (String) tblListing.getValueAt(selectedRow, 0);
        return system.getListingDirectory().findById(listingId);
    }
}
