/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import UI.main.LoginPage;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Organization;
import basement_class.Enterprise_2.Listing;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bob-h
 */
public class BuyerJPanel extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    
    // Shopping cart
    private List<Listing> shoppingCart;
    
    // Work area panels
    private BrowseWorkArea browsePanel;
    private ShoppongCartWorkArea cartPanel;
    private PersonalJPanel personalPanel;
    
    // Track current panel
    private String currentPanel;
    
    public BuyerJPanel(BuyerAccount buyerAccount, 
                       Organization organization, 
                       Enterprise enterprise, 
                       EcoSystem system) {
        this.buyerAccount = buyerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.shoppingCart = new ArrayList<>();  // Initialize shopping cart
        this.currentPanel = "";
        
        initComponents();
        
        // Initialize work area panels
        initializeWorkAreaPanels();
        
        // Show browse by default
        showBrowsePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        functionJPanel = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        btnShoppingCart = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnSwitch = new javax.swing.JButton();
        btnSearchPage = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(204, 255, 204));
        controlJPanel.setForeground(new java.awt.Color(204, 255, 204));
        controlJPanel.setToolTipText("");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse products");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnShoppingCart.setText("Shopping Cart");
        btnShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoppingCartActionPerformed(evt);
            }
        });

        btnPersonal.setText("Personal Information");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnSwitch.setText("Switch");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnSearchPage.setText("Search Page");
        btnSearchPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout))
                    .addComponent(btnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShoppingCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );

        functionJPanel.setLeftComponent(controlJPanel);

        workArea.setLayout(new java.awt.CardLayout());
        functionJPanel.setRightComponent(workArea);

        add(functionJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // Show browse panel
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "BrowseCard");
        currentPanel = "BrowseCard";

        // Refresh listings
        if (browsePanel != null) {
            browsePanel.refreshListings();
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoppingCartActionPerformed
        // Switch to personal information panel
        showShoppingCart();
    }//GEN-LAST:event_btnShoppingCartActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        // Switch to personal information panel
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "PersonalCard");
        currentPanel = "PersonalCard";
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        mainFrame.dispose();

        LoginPage loginPage = new LoginPage(system);
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // Switch to TrackJPanel (Order Tracker role)
        TrackJPanel trackPanel = new TrackJPanel(
            buyerAccount, organization, enterprise, system
        );

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.setContentPane(trackPanel);
            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_btnSwitchActionPerformed

    private void btnSearchPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPageActionPerformed
        // Switch to ProductSearchJPanel
        ProductSearchJPanel searchPanel = new ProductSearchJPanel(
            buyerAccount, organization, enterprise, system
        );

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.setContentPane(searchPanel);
            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_btnSearchPageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnSearchPage;
    private javax.swing.JButton btnShoppingCart;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane functionJPanel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    /**
     * Initialize work area panels with CardLayout
     */
    private void initializeWorkAreaPanels() {
        // Create panels - pass 'this' as parent reference
        browsePanel = new BrowseWorkArea(buyerAccount, system, this);
        cartPanel = new ShoppongCartWorkArea(buyerAccount, system, shoppingCart);
        personalPanel = new PersonalJPanel(buyerAccount, system);

        // Set CardLayout if not already set
        workArea.setLayout(new CardLayout());

        // Clear and add panels
        workArea.removeAll();
        workArea.add(browsePanel, "BrowseCard");
        workArea.add(cartPanel, "CartCard");
        workArea.add(personalPanel, "PersonalCard");
    }

    /**
     * Show browse panel (default view)
     */
    void showBrowsePanel() {
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "BrowseCard");
        currentPanel = "BrowseCard";
    }
    
    /**
     * Show shopping cart panel
     * Called by BrowseWorkArea when user clicks "Check out"
     */
    public void showShoppingCart() {
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "CartCard");
        currentPanel = "CartCard";
        
        // Refresh cart
        if (cartPanel != null) {
            cartPanel.refreshCart();
        }
    }
    
    /**
     * Show detail panel for a listing
     * Called by BrowseWorkArea when user clicks "Detailed"
     */
    public void showDetailPanel(ListingDetailWorkArea detailPanel) {
        // Add detail panel to card layout
        workArea.add(detailPanel, "DetailCard");
        
        // Show detail panel
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "DetailCard");
        currentPanel = "DetailCard";
    }
    
    /**
     * Hide detail panel and return to browse
     * Called by ListingDetailWorkArea when user clicks "Back"
     */
    public void hideDetailPanel() {
        // Remove detail card if it exists
        CardLayout cl = (CardLayout) workArea.getLayout();
        
        // Show browse panel
        cl.show(workArea, "BrowseCard");
        currentPanel = "BrowseCard";
        
        // Refresh browse listings
        if (browsePanel != null) {
            browsePanel.refreshListings();
        }
    }
    
    /**
     * Add listing to shopping cart
     * Called by BrowseWorkArea when user clicks "Add"
     */
    public void addToCart(Listing listing) {
        if (listing == null) {
            return;
        }
    
        // Check if already in cart
        for (Listing item : shoppingCart) {
            if (item.getId().equals(listing.getId())) {
                JOptionPane.showMessageDialog(this,
                    "This item is already in your cart",
                    "Already in Cart",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
    
        // Add to cart
        shoppingCart.add(listing);

        JOptionPane.showMessageDialog(this,
            "Added to cart: " + listing.getTitle(),
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Get shopping cart (for external access)
     */
    public List<Listing> getShoppingCart() {
        return shoppingCart;
    }

    /**
     * Get current buyer account
     */
    public BuyerAccount getBuyerAccount() {
        return buyerAccount;
    }

    /**
     * Get system
     */
    public EcoSystem getSystem() {
        return system;
    }
    
    public void showReportPanel(JPanel reportPanel) {
        workArea.add(reportPanel, "ReportCard");
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ReportCard");
        currentPanel = "ReportCard";
    }
    
    public void showChatPanel(javax.swing.JPanel chatPanel) {
        workArea.add(chatPanel, "ChatCard");
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "ChatCard");
        currentPanel = "ChatCard";
    }
}
