/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import UI.main.LoginPage;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.*;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_1.Account.BuyerProfile;
import basement_class.Enterprise_1.Role.*;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_2.ListingDirectory;
import basement_class.DAO.OrderDao;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bob-h
 */
public class BuyerJPanel extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    
    // Shopping cart - stores selected listings
    private List<Listing> shoppingCart;
    
    // References to work area panels
    private BrowseWorkArea browsePanel;
    private ShoppongCartWorkArea cartPanel;
    private PersonalJPanel personalPanel;
    
    // Current active panel (to know which panel is showing)
    private String currentPanel;
    /**
     * Creates new form BuyerJPanel
     */
    public BuyerJPanel(BuyerAccount buyerAccount,Organization organization, Enterprise enterprise, EcoSystem system) {
        this.buyerAccount = buyerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.shoppingCart = new ArrayList<>();
        this.currentPanel = "";
        
        initComponents();
        
        // Initialize work area panels
        initializeWorkAreaPanels();
        
        // Show browse panel by default
        showBrowsePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        functionJPanel = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        btnShoppingCart = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        btnSwitch = new javax.swing.JButton();
        btnAddFavorites = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(204, 255, 204));
        controlJPanel.setForeground(new java.awt.Color(204, 255, 204));
        controlJPanel.setToolTipText("");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse products");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnShoppingCart.setText("Shopping Cart");
        btnShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoppingCartActionPerformed(evt);
            }
        });

        btnPersonal.setText("Personal Information");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Advanced Search", "Order History" }));

        btnSwitch.setText("Switch");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnAddFavorites.setText("Add to favorites");
        btnAddFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavoritesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout))
                    .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddFavorites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShoppingCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddFavorites)
                .addGap(138, 138, 138)
                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );

        functionJPanel.setLeftComponent(controlJPanel);

        workArea.setLayout(new java.awt.CardLayout());
        functionJPanel.setRightComponent(workArea);

        add(functionJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        showBrowsePanel();
        browsePanel.refreshListings();  // Reload listings
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoppingCartActionPerformed
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "CartCard");
        currentPanel = "CartCard";
        updateButtonStates();

        // Refresh cart display
        cartPanel.refreshCart();
    }//GEN-LAST:event_btnShoppingCartActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "PersonalCard");
        currentPanel = "PersonalCard";
        updateButtonStates();

        // Refresh personal info
        personalPanel.loadPersonalInfo();
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            if (frame != null) {
                // Don't create new LoginPage - use CardLayout to go back
                // Or save the original LoginPage reference

                // For now, recreate but don't re-initialize
                LoginPage loginPage = new LoginPage();
                frame.setContentPane(loginPage.getContentPane());
                frame.revalidate();
                frame.repaint();
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavoritesActionPerformed
        // TODO add your handling code here:
        if (!isOnBrowsePanel()) {
            JOptionPane.showMessageDialog(this,
                "Please go to Browse Products to add favorites",
                "Not Available",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get selected listing from browse panel
        Listing selected = browsePanel.getSelectedListing();
        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a listing first",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Add to buyer's favorites
        buyerAccount.addToFavorites(selected.getId());

        JOptionPane.showMessageDialog(this,
            "Added to favorites: " + selected.getTitle(),
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddFavoritesActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
        String selectedRole = (String) cmbRole.getSelectedItem();
    
        if (selectedRole == null) {
            return;
        }

        Role newRole = null;

        if (selectedRole.equals("Advanced Search")) {
            newRole = new ProductSearcherRole();
        } else if (selectedRole.equals("Order History")) {
            newRole = new OrderTrackerRole();
        } else {
            // Already in Buyer role
            return;
        }

        // Update account role
        buyerAccount.setRole(newRole);

        // Create new work area
        JPanel newWorkArea = newRole.createWorkArea(
            buyerAccount, organization, enterprise, system
        );

        // Switch content
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.setContentPane(newWorkArea);
            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_btnSwitchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFavorites;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnShoppingCart;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane functionJPanel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private void initializeWorkAreaPanels() {
        // Create panels
        browsePanel = new BrowseWorkArea(buyerAccount, system, this);
        cartPanel = new ShoppongCartWorkArea(buyerAccount, system, shoppingCart);
        personalPanel = new PersonalJPanel(buyerAccount, system);
        
        // Add to workArea with CardLayout
        workArea.removeAll();
        workArea.setLayout(new CardLayout());
        workArea.add(browsePanel, "BrowseCard");
        workArea.add(cartPanel, "CartCard");
        workArea.add(personalPanel, "PersonalCard");
    }
    
        /**
     * Get shopping cart
     */
    public List<Listing> getShoppingCart() {
        return shoppingCart;
    }
    
    /**
     * Add listing to shopping cart
     */
    public void addToCart(Listing listing) {
        if (!shoppingCart.contains(listing)) {
            shoppingCart.add(listing);
            JOptionPane.showMessageDialog(this, 
                "Added to cart: " + listing.getTitle(),
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
        /**
     * Check if currently on browse panel
     */
    public boolean isOnBrowsePanel() {
        return "BrowseCard".equals(currentPanel);
    }
    
    /**
     * Show browse panel
     */
    private void showBrowsePanel() {
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.show(workArea, "BrowseCard");
        currentPanel = "BrowseCard";
        updateButtonStates();
    }
    
    /**
     * Update button states based on current panel
     */
    private void updateButtonStates() {
        // Enable/disable "Add to favorites" based on current panel
        btnAddFavorites.setEnabled(isOnBrowsePanel());
    }
}
