/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import UI.Enterprise4.BuyerSellerChatPanel;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Enterprise_4.CommunicationServiceOrganization;
import basement_class.Enterprise_4.HelpCenterEnterprise;
import basement_class.Enterprise_4.MessageDirectory;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author bob-h
 */
public class ListingDetailWorkArea extends javax.swing.JPanel {

    private Listing listing;
    private BuyerAccount buyerAccount;
    private EcoSystem system;
    private BuyerJPanel parentPanel;
    /**
     * Creates new form ListingDetailWorkArea
     */
    public ListingDetailWorkArea(Listing listing, BuyerAccount buyerAccount,EcoSystem system, BuyerJPanel parentPanel) {
        this.listing = listing;
        this.buyerAccount = buyerAccount;
        this.system = system;
        this.parentPanel = parentPanel;
        
        initComponents();
        rbnYes.setEnabled(false);
        rbnNo.setEnabled(false);
        
        // Load listing details
        loadListingDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        ListingJpanel = new javax.swing.JPanel();
        lblListingID = new javax.swing.JLabel();
        txtListingID = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblNego = new javax.swing.JLabel();
        rbnYes = new javax.swing.JRadioButton();
        rbnNo = new javax.swing.JRadioButton();
        lblDescri = new javax.swing.JLabel();
        DescriJpanel = new javax.swing.JScrollPane();
        txtAreaDescri = new javax.swing.JTextArea();
        lblSellerUser = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblFavoriteCount = new javax.swing.JLabel();
        lblPostedDate = new javax.swing.JLabel();
        txtSellerUser = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        txtFavoriteCount = new javax.swing.JTextField();
        txtPostedDate = new javax.swing.JTextField();
        btnTalkWithUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddfavorite = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        PhotoJpanel = new javax.swing.JPanel();
        Picture = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Title");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTitle, java.awt.BorderLayout.CENTER);

        jSplitPane1.setTopComponent(jPanel1);

        ListingJpanel.setBackground(new java.awt.Color(255, 255, 255));

        lblListingID.setText("Listing ID：");

        lblPrice.setText("Price:");

        lblNego.setText("Is Negotiable?");

        rbnYes.setText("Yes");
        rbnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnYesActionPerformed(evt);
            }
        });

        rbnNo.setText("No");
        rbnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnNoActionPerformed(evt);
            }
        });

        lblDescri.setText("Description:");

        txtAreaDescri.setColumns(20);
        txtAreaDescri.setRows(5);
        DescriJpanel.setViewportView(txtAreaDescri);

        lblSellerUser.setText("Seller Username:");

        lblRating.setText("Seller Rating:");

        lblFavoriteCount.setText("Favorite Count:");

        lblPostedDate.setText("Posted Date:");

        btnTalkWithUser.setText("Talk with Seller");
        btnTalkWithUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTalkWithUserActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddfavorite.setText("Add");
        btnAddfavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddfavoriteActionPerformed(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListingJpanelLayout = new javax.swing.GroupLayout(ListingJpanel);
        ListingJpanel.setLayout(ListingJpanelLayout);
        ListingJpanelLayout.setHorizontalGroup(
            ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListingJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListingJpanelLayout.createSequentialGroup()
                        .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(lblNego))
                        .addGap(30, 30, 30)
                        .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ListingJpanelLayout.createSequentialGroup()
                                .addComponent(rbnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbnNo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPrice)))
                    .addComponent(DescriJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(ListingJpanelLayout.createSequentialGroup()
                        .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescri)
                            .addComponent(lblSellerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFavoriteCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPostedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSellerUser)
                            .addComponent(txtRating, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFavoriteCount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPostedDate, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(ListingJpanelLayout.createSequentialGroup()
                        .addComponent(lblListingID)
                        .addGap(47, 47, 47)
                        .addComponent(txtListingID))
                    .addGroup(ListingJpanelLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddfavorite))
                    .addGroup(ListingJpanelLayout.createSequentialGroup()
                        .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTalkWithUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListingJpanelLayout.setVerticalGroup(
            ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListingJpanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAddfavorite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListingID)
                    .addComponent(txtListingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnYes)
                    .addComponent(rbnNo)
                    .addComponent(lblNego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellerUser)
                    .addComponent(txtSellerUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRating)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFavoriteCount)
                    .addComponent(txtFavoriteCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListingJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostedDate)
                    .addComponent(txtPostedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTalkWithUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(ListingJpanel);

        PhotoJpanel.setBackground(new java.awt.Color(255, 255, 255));

        Picture.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        Picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PhotoJpanelLayout = new javax.swing.GroupLayout(PhotoJpanel);
        PhotoJpanel.setLayout(PhotoJpanelLayout);
        PhotoJpanelLayout.setHorizontalGroup(
            PhotoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );
        PhotoJpanelLayout.setVerticalGroup(
            PhotoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(PhotoJpanel);

        jSplitPane1.setRightComponent(jSplitPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Go back to browse view
        if (parentPanel != null) {
            parentPanel.hideDetailPanel();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTalkWithUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTalkWithUserActionPerformed
        // Start a chat with the seller of this listing

        // Basic checks
        if (listing == null || buyerAccount == null) {
            JOptionPane.showMessageDialog(this,
                    "Listing or buyer information is missing.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1) Get the seller of this listing
        UserAccount seller = listing.getSeller();
        if (seller == null) {
            JOptionPane.showMessageDialog(this,
                    "This listing does not have a seller assigned.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2) Wrap the seller into an ArrayList<UserAccount>
        //    Because BuyerSellerChatPanel expects a list of partners
        ArrayList<UserAccount> partners = new ArrayList<>();
        partners.add(seller);

        // 3) Get the global MessageDirectory (you or your teammate
        //    should make sure EcoSystem provides this method)
        MessageDirectory messageDirectory = system.getMessageDirectory();

        // 4) Find the CommunicationServiceOrganization (chat backend)
        CommunicationServiceOrganization commOrg = findCommunicationServiceOrg(system);
        if (commOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "CommunicationServiceOrganization was not found in the system.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5) Create the chat panel
        BuyerSellerChatPanel chatPanel = new BuyerSellerChatPanel(
                buyerAccount,          // current user (buyer)
                partners,              // one partner: the seller
                messageDirectory,      // message storage
                commOrg                // organization that processes chat / flags
        );

        // 6) Show chat panel via the parent BuyerJPanel (CardLayout)
        parentPanel.showChatPanel(chatPanel);
    }//GEN-LAST:event_btnTalkWithUserActionPerformed

    private void btnAddfavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddfavoriteActionPerformed
        // TODO add your handling code here:
        // Add or remove from favorites
        if (listing == null) {
            return;
        }
        
        String listingId = listing.getId();
        
        // Check if already in favorites
        if (buyerAccount.isFavorite(listingId)) {
            // Remove from favorites
            buyerAccount.removeFromFavorites(listingId);
            btnAddfavorite.setText("Add to Favorites");
            JOptionPane.showMessageDialog(this,
                "Removed from favorites",
                "Favorites Updated",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Add to favorites
            buyerAccount.addToFavorites(listingId);
            btnAddfavorite.setText("Remove from Favorites");
            JOptionPane.showMessageDialog(this,
                "Added to favorites",
                "Favorites Updated",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddfavoriteActionPerformed

    private void rbnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnYesActionPerformed

    private void rbnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnNoActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        if (listing == null || buyerAccount == null) {
            JOptionPane.showMessageDialog(this,
                "Missing user or listing information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserAccount seller = listing.getSeller();

        ReportViolationWorkArea reportPanel = new ReportViolationWorkArea(
                buyerAccount,
                seller,
                listing,
                system,
                parentPanel
        );

        parentPanel.showReportPanel(reportPanel);
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DescriJpanel;
    private javax.swing.JPanel ListingJpanel;
    private javax.swing.JPanel PhotoJpanel;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton btnAddfavorite;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTalkWithUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblDescri;
    private javax.swing.JLabel lblFavoriteCount;
    private javax.swing.JLabel lblListingID;
    private javax.swing.JLabel lblNego;
    private javax.swing.JLabel lblPostedDate;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblSellerUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbnNo;
    private javax.swing.JRadioButton rbnYes;
    private javax.swing.JTextArea txtAreaDescri;
    private javax.swing.JTextField txtFavoriteCount;
    private javax.swing.JTextField txtListingID;
    private javax.swing.JTextField txtPostedDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtSellerUser;
    // End of variables declaration//GEN-END:variables

    /**
     * Load listing details into UI components
     */
    private void loadListingDetails() {
        if (listing == null) {
            return;
        }
        
        // Set title
        lblTitle.setText(listing.getTitle());
        
        // Basic information (no category/condition for second-hand items)
        txtListingID.setText(listing.getId());
        txtPrice.setText(String.format("$%.2f", listing.getPrice()));
        
        // Negotiable (placeholder - assume yes for second-hand)
        rbnYes.setSelected(true);
        rbnNo.setSelected(false);
        
        // Description
        txtAreaDescri.setText(listing.getDescription());
        
        // Seller information
        if (listing.getSeller() != null) {
            txtSellerUser.setText(listing.getSeller().getUsername());
        }
        txtRating.setText("4.5/5.0"); // Placeholder rating
        
        // Check if in favorites and update button text
        if (buyerAccount.isFavorite(listing.getId())) {
            btnAddfavorite.setText("Remove from Favorites");
        } else {
            btnAddfavorite.setText("Add to Favorites");
        }
        
        txtFavoriteCount.setText("N/A"); // Placeholder
        
        // Posted date
        if (listing.getSubmitTime() != null) {
            txtPostedDate.setText(listing.getSubmitTime().toString());
        } else {
            txtPostedDate.setText("N/A");
        }
        
        // Load image
        loadImage();
    }
    
    /**
     * Load product image
     */
    private void loadImage() {
        if (listing == null) {
            Picture.setText("No Image Available");
            return;
        }
        
        String imagePath = listing.getImagePath();
        if (imagePath != null && !imagePath.isEmpty()) {
            File imageFile = new File(imagePath);
            if (imageFile.exists()) {
                try {
                    ImageIcon icon = new ImageIcon(imagePath);
                    Image img = icon.getImage();
                    // Scale image to fit label (600x600)
                    Image scaledImg = img.getScaledInstance(600, 600, Image.SCALE_SMOOTH);
                    Picture.setIcon(new ImageIcon(scaledImg));
                    Picture.setText("");
                } catch (Exception e) {
                    Picture.setText("Image Load Error");
                }
            } else {
                Picture.setText("No Image Available");
            }
        } else {
            Picture.setText("No Image Available");
        }
    }
    
    private CommunicationServiceOrganization findCommunicationServiceOrg(EcoSystem system) {

        if (system == null) {
            return null;
        }

        // Search through all networks → enterprises → organizations
        for (Network net : system.getNetworks()) {
            for (Enterprise ent : net.getEnterprises()) {

                // Loop through organizations inside this enterprise
                for (Organization org : ent.getOrganizations()) {

                    // Check if this org is the communication service org
                    if (org instanceof CommunicationServiceOrganization) {
                        return (CommunicationServiceOrganization) org;
                    }
                }
            }
        }

        // Not found
        return null;
    }
}
