/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_1.Account.BuyerProfile;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.WorkRequest.AccountStatusReviewRequest;
import basement_class.Network;
import basement_class.Organization;
import javax.swing.JOptionPane;

/**
 *
 * @author bob-h
 */
public class PersonalJPanel extends javax.swing.JPanel {
    
    private final EcoSystem system;
    private final BuyerAccount buyer;

    private String originalName;
    private String originalEmail;
    private String originalPhone;
    private String originalLocation;
    private String originalPayment;
    private double originalBudget;
    /**
     * Creates new form PersonalJPanel
     */
    public PersonalJPanel(BuyerAccount buyer,EcoSystem system) {
        initComponents();
        this.system = system;
        this.buyer = buyer;

        populateFields();
        setEditing(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblOrders = new javax.swing.JLabel();
        lblCompletedOrders = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        lblSpending = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtOrders = new javax.swing.JTextField();
        txtCompletedOrders = new javax.swing.JTextField();
        txtPoints = new javax.swing.JTextField();
        txtSpending = new javax.swing.JTextField();
        txtBudget = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtPayment = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        lblAccountActivity = new javax.swing.JLabel();
        cmbAccountActivity = new javax.swing.JComboBox<>();
        lblRequestDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRequestDescription = new javax.swing.JTextArea();

        lblName.setText("Full Name：");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone Number:");

        lblUserName.setText("Username:");

        lblID.setText("User ID:");

        lblStatus.setText("Account Status:");

        lblTime.setText("Member Since:");

        lblOrders.setText("Total Orders:");

        lblCompletedOrders.setText("Completed Orders:");

        lblPoints.setText("Reward Points:");

        lblSpending.setText("Total Spending:");

        lblBudget.setText("Max Budget:");

        lblLocation.setText("Preferred Location:");

        lblPayment.setText("Preferred Payment:");

        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Change Password");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        btnClose.setText("Close Account");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblAccountActivity.setText("Account Activity：");

        cmbAccountActivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "suspend", "reactivate", "ban" }));
        cmbAccountActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountActivityActionPerformed(evt);
            }
        });

        lblRequestDescription.setText("Request Description：");

        txtRequestDescription.setColumns(20);
        txtRequestDescription.setRows(5);
        jScrollPane1.setViewportView(txtRequestDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBudget, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSpending, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoints, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCompletedOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtCompletedOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtSpending, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAccountActivity)
                                .addGap(40, 40, 40)
                                .addComponent(cmbAccountActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClose)
                            .addComponent(lblRequestDescription)
                            .addComponent(jScrollPane1)))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccountActivity)
                    .addComponent(cmbAccountActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrders)
                            .addComponent(txtOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompletedOrders)
                            .addComponent(txtCompletedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoints)
                            .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpending)
                            .addComponent(txtSpending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBudget)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPayment)
                            .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangePassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void cmbAccountActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccountActivityActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        if (buyer == null) return;

        String action = (String) cmbAccountActivity.getSelectedItem(); // 例如 "suspend"
        String desc = txtRequestDescription.getText().trim();

        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please describe your request.",
                    "Missing Description",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to submit this request? (" + action + ")",
                "Confirm",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        AccountStatusReviewRequest req =
                new AccountStatusReviewRequest(buyer, action, desc);
        req.setSender(buyer);             

        UserControlOrganization userOrg = findUserControlOrg();
        if (userOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "UserControlOrganization not found. Cannot submit request.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        userOrg.getWorkRequestDirectory().addWorkRequest(req);

        system.getWorkRequestDirectory().addWorkRequest(req);

        JOptionPane.showMessageDialog(this,
                "Your account status request has been submitted.",
                "Request Submitted",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setEditing(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtName.setText(originalName);
        txtEmail.setText(originalEmail);
        txtPhone.setText(originalPhone);
        txtLocation.setText(originalLocation);
        txtPayment.setText(originalPayment);
        txtBudget.setText(String.valueOf(originalBudget));

        setEditing(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (buyer == null) return;

        // Get input values
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String location = txtLocation.getText().trim();
        String payment = txtPayment.getText().trim();
        String budgetStr = txtBudget.getText().trim();

        // ==========================================
        // VALIDATION 1: Required fields
        // ==========================================
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Full Name is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Email is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return;
        }

        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Phone Number is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
            return;
        }

        // ==========================================
        // VALIDATION 2: Name format (letters and spaces only)
        // ==========================================
        if (!name.matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(this,
                "Full Name can only contain letters and spaces.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return;
        }

        // Name length limit
        if (name.length() < 2 || name.length() > 50) {
            JOptionPane.showMessageDialog(this,
                "Full Name must be between 2 and 50 characters.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return;
        }

        // ==========================================
        // VALIDATION 3: Email format
        // ==========================================
        // Basic email pattern: xxx@xxx.xxx
        String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email address.\n" +
                "Format: example@university.edu",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return;
        }

        // Email length limit
        if (email.length() > 100) {
            JOptionPane.showMessageDialog(this,
                "Email address is too long (max 100 characters).",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return;
        }

        // ==========================================
        // VALIDATION 4: Phone number format
        // ==========================================
        // Remove spaces and dashes for validation
        String cleanPhone = phone.replaceAll("[\\s-]", "");

        // Check if it contains only digits (and optional + at start)
        if (!cleanPhone.matches("^\\+?\\d{10,15}$")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid phone number.\n" +
                "Format: 123-456-7890 or +1234567890\n" +
                "Must be 10-15 digits.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
            return;
        }

        // ==========================================
        // VALIDATION 5: Budget (must be number >= 0)
        // ==========================================
        double budget;
        try {
            budget = Double.parseDouble(budgetStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Max Budget must be a valid number.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtBudget.requestFocus();
            return;
        }

        // Budget must be non-negative
        if (budget < 0) {
            JOptionPane.showMessageDialog(this,
                "Max Budget cannot be negative.\n" +
                "Enter 0 for unlimited budget.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtBudget.requestFocus();
            return;
        }

        // Budget reasonable limit (optional)
        if (budget > 1000000) {
            int confirm = JOptionPane.showConfirmDialog(this,
                "Budget is very high ($" + String.format("%.2f", budget) + ").\n" +
                "Are you sure?",
                "Confirm Budget",
                JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                txtBudget.requestFocus();
                return;
            }
        }

        // ==========================================
        // VALIDATION 6: Location (optional but with length limit)
        // ==========================================
        if (!location.isEmpty() && location.length() > 100) {
            JOptionPane.showMessageDialog(this,
                "Preferred Location is too long (max 100 characters).",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtLocation.requestFocus();
            return;
        }

        // ==========================================
        // VALIDATION 7: Payment method (optional but with length limit)
        // ==========================================
        if (!payment.isEmpty() && payment.length() > 50) {
            JOptionPane.showMessageDialog(this,
                "Preferred Payment Method is too long (max 50 characters).",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            txtPayment.requestFocus();
            return;
        }

        // ==========================================
        // ALL VALIDATIONS PASSED - Save data
        // ==========================================
        BuyerProfile profile = buyer.getProfile();
        profile.setFullName(name);
        profile.setEmail(email);
        profile.setPhoneNumber(phone);
        profile.setPreferredLocation(location);
        profile.setMaxBudget(budget);
        profile.setPreferredPaymentMethod(payment);

        // Also update UserAccount level
        buyer.setEmail(email);
        buyer.setPhoneNumber(phone);

        // Update original values for cancel functionality
        originalName = name;
        originalEmail = email;
        originalPhone = phone;
        originalLocation = location;
        originalPayment = payment;
        originalBudget = budget;

        // Refresh display and disable editing
        populateFields();
        setEditing(false);

        JOptionPane.showMessageDialog(this,
            "Profile saved successfully!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAccountActivity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountActivity;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblCompletedOrders;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblRequestDescription;
    private javax.swing.JLabel lblSpending;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtCompletedOrders;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrders;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoints;
    private javax.swing.JTextArea txtRequestDescription;
    private javax.swing.JTextField txtSpending;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        if (buyer == null) return;

        BuyerProfile profile = buyer.getProfile();

        txtName.setText(profile.getFullName());
        txtEmail.setText(profile.getEmail());
        txtPhone.setText(profile.getPhoneNumber());
        txtUserName.setText(buyer.getUsername());
        txtID.setText(buyer.getUserId());
        txtStatus.setText(buyer.getStatus());
        if (buyer.getCreatedAt() != null) {
            txtTime.setText(buyer.getCreatedAt().toString());
        } else {
            txtTime.setText("N/A");
        }

        txtOrders.setText(String.valueOf(buyer.getTotalPurchases()));
        txtCompletedOrders.setText(String.valueOf(buyer.getCompletedPurchases()));
        txtPoints.setText(String.valueOf(buyer.getPoints()));

        txtSpending.setText(String.format("%.2f", buyer.getTotalSpending()));

        txtBudget.setText(String.valueOf(profile.getMaxBudget()));
        txtLocation.setText(profile.getPreferredLocation());
        txtPayment.setText(profile.getPreferredPaymentMethod());

        txtPassword.setText("********");

        originalName = txtName.getText();
        originalEmail = txtEmail.getText();
        originalPhone = txtPhone.getText();
        originalLocation = txtLocation.getText();
        originalPayment = txtPayment.getText();
        try {
            originalBudget = Double.parseDouble(txtBudget.getText());
        } catch (NumberFormatException e) {
            originalBudget = 0.0;
        }
    }
    
    public void refreshProfile() {
        populateFields();
    }
    
    private void setEditing(boolean editing) {
        txtName.setEditable(editing);
        txtEmail.setEditable(editing);
        txtPhone.setEditable(editing);
        txtBudget.setEditable(editing);
        txtLocation.setEditable(editing);
        txtPayment.setEditable(editing);

        txtUserName.setEditable(false);
        txtID.setEditable(false);
        txtStatus.setEditable(false);
        txtTime.setEditable(false);
        txtOrders.setEditable(false);
        txtCompletedOrders.setEditable(false);
        txtPoints.setEditable(false);
        txtSpending.setEditable(false);
        txtPassword.setEditable(false);

        btnEdit.setEnabled(!editing);
        btnSave.setEnabled(editing);
        btnCancel.setEnabled(editing);
        btnChangePassword.setEnabled(true);
        btnClose.setEnabled(true);
    }
    
    private UserControlOrganization findUserControlOrg() {
        for (Network net : system.getNetworks()) {
            for (Enterprise ent : net.getEnterprises()) {
                for (Organization org : ent.getOrganizations()) {
                    if (org instanceof UserControlOrganization) {
                        return (UserControlOrganization) org;
                    }
                }
            }
        }
        return null;
    }
    
    
}
