/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Organization;
import basement_class.UserAccount;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author bob-h
 */
public class ProductSearchJPanel extends javax.swing.JPanel {
    
    private BuyerAccount buyerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private BuyerJPanel parentPanel;  // used for CardLayout back navigation

    private List<Listing> allListings;   // source listings
        /**
     * Creates new form ProductSearchJPanel
     */
    public ProductSearchJPanel(BuyerAccount buyerAccount,
                           Organization organization,
                           Enterprise enterprise,
                           EcoSystem system,
                           BuyerJPanel parentPanel) {

        initComponents();
        this.buyerAccount = buyerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.parentPanel = parentPanel;

        // Load all listings from system listing directory
        this.allListings = system.getListingDirectory().getListings();

        populateCategoryCombo();
        populateConditionCombo();
        populateSortCombo();

        refreshTable(allListings);  // show all initially
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblKeyword = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPriceRange = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        txtLowPrice = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtHighPrice = new javax.swing.JTextField();
        cmbCondition = new javax.swing.JComboBox<>();
        cmbSort = new javax.swing.JComboBox<>();
        btnReserch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();
        btnDetailed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Advanced Product Search ");
        jPanel2.add(lblTitle, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel2);

        lblKeyword.setText("Keyword: ");

        lblCategory.setText("Category: ");

        lblPriceRange.setText("Price Range:");

        lblCondition.setText("Condition:");

        jLabel6.setText("Sort By:");

        lblTo.setText("to");

        btnReserch.setText("Search");

        btnReset.setText("Reset");

        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Title ", "Category", "Price", "Status "
            }
        ));
        jScrollPane1.setViewportView(tblSearchResult);

        btnDetailed.setText("Detailed");

        jButton1.setText("Add To Cart");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReserch)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPriceRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKeyword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKeyword)
                            .addComponent(cmbCategory, 0, 145, Short.MAX_VALUE)
                            .addComponent(txtLowPrice)
                            .addComponent(cmbCondition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHighPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetailed)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeyword)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPriceRange)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTo)
                        .addComponent(txtHighPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondition)
                    .addComponent(cmbCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserch)
                    .addComponent(btnReset)
                    .addComponent(btnDetailed)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane2, "card2");

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailed;
    private javax.swing.JButton btnReserch;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbCondition;
    private javax.swing.JComboBox<String> cmbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblKeyword;
    private javax.swing.JLabel lblPriceRange;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTextField txtHighPrice;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JTextField txtLowPrice;
    // End of variables declaration//GEN-END:variables

    private void populateCategoryCombo() {
        cmbCategory.removeAllItems();
        cmbCategory.addItem("All");
        cmbCategory.addItem("Electronics");
        cmbCategory.addItem("Clothes");
        cmbCategory.addItem("Furniture");
        cmbCategory.addItem("Food");
        // add more if needed
    }

    private void populateConditionCombo() {
        cmbCondition.removeAllItems();
        cmbCondition.addItem("All");
        cmbCondition.addItem("New");
        cmbCondition.addItem("Used - Like New");
        cmbCondition.addItem("Used");
    }

    private void populateSortCombo() {
        cmbSort.removeAllItems();
        cmbSort.addItem("Sort by: Default");
        cmbSort.addItem("Price: Low to High");
        cmbSort.addItem("Price: High to Low");
        cmbSort.addItem("Name: A → Z");
        cmbSort.addItem("Name: Z → A");
    }
    
    private void performSearch() {

        String keyword = txtKeyword.getText().trim().toLowerCase();
        String category = cmbCategory.getSelectedItem().toString();
        String condition = cmbCondition.getSelectedItem().toString();

        double low = 0;
        double high = Double.MAX_VALUE;

        try {
            if (!txtLowPrice.getText().trim().isEmpty()) {
                low = Double.parseDouble(txtLowPrice.getText().trim());
            }
            if (!txtHighPrice.getText().trim().isEmpty()) {
                high = Double.parseDouble(txtHighPrice.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Invalid price range.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // filter
        List<Listing> results = new ArrayList<>();

        for (Listing l : allListings) {
            boolean match = true;

            if (!keyword.isEmpty() &&
                    !l.getTitle().toLowerCase().contains(keyword)) {
                match = false;
            }

            if (!category.equals("All") &&
                    !l.getCategory().equalsIgnoreCase(category)) {
                match = false;
            }

            if (!condition.equals("All") &&
                    !l.getCondition().equalsIgnoreCase(condition)) {
                match = false;
            }

            if (l.getPrice() < low || l.getPrice() > high) {
                match = false;
            }

            if (match) {
                results.add(l);
            }
        }

        applySort(results);
        refreshTable(results);
    }
}
