/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_2.Listing;
import basement_class.Organization;
import basement_class.UserAccount;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bob-h
 */
public class ProductSearchJPanel extends javax.swing.JPanel {
    
    private BuyerAccount buyerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private BuyerJPanel parentPanel;  // used for CardLayout back navigation

    private List<Listing> allListings;   // source listings
        /**
     * Creates new form ProductSearchJPanel
     */
    public ProductSearchJPanel(BuyerAccount buyerAccount,
                           Organization organization,
                           Enterprise enterprise,
                           EcoSystem system,
                           BuyerJPanel parentPanel) {

        initComponents();
        this.buyerAccount = buyerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.parentPanel = parentPanel;

        this.allListings = system.getListingDirectory().getListingList();

        populateSortCombo();      // keep sort
        // category / condition are no longer used

        refreshTable(allListings);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblKeyword = new javax.swing.JLabel();
        lblPriceRange = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        txtLowPrice = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtHighPrice = new javax.swing.JTextField();
        cmbSort = new javax.swing.JComboBox<>();
        btnReserch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();
        btnDetailed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Advanced Product Search ");
        jPanel2.add(lblTitle, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel2);

        lblKeyword.setText("Keyword: ");

        lblPriceRange.setText("Price Range:");

        jLabel6.setText("Sort By:");

        lblTo.setText("to");

        btnReserch.setText("Search");
        btnReserch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserchActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Name", "Price", "Status", "Seller"
            }
        ));
        jScrollPane1.setViewportView(tblSearchResult);

        btnDetailed.setText("Detailed");
        btnDetailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailedActionPerformed(evt);
            }
        });

        jButton1.setText("Add To Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReserch)
                            .addComponent(lblKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetailed))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPriceRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLowPrice)
                            .addComponent(cmbSort, 0, 145, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHighPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeyword)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPriceRange)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTo)
                        .addComponent(txtHighPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserch)
                    .addComponent(btnReset)
                    .addComponent(btnDetailed)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane2, "card2");

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserchActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_btnReserchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtKeyword.setText("");
        txtLowPrice.setText("");
        txtHighPrice.setText("");

        if (cmbSort.getItemCount() > 0) {
            cmbSort.setSelectedIndex(0);
        }

        refreshTable(allListings);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDetailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailedActionPerformed
        // TODO add your handling code here:
        Listing selected = getSelectedListing();
        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a listing first.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (parentPanel == null) {
            JOptionPane.showMessageDialog(this,
                    "Parent buyer panel is not available.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a detail panel for the selected listing
        ListingDetailWorkArea detailPanel = new ListingDetailWorkArea(
                selected,
                buyerAccount,
                system,
                parentPanel
        );

        // Show the detail panel via Buyer's CardLayout
        parentPanel.showDetailPanel(detailPanel);
    }//GEN-LAST:event_btnDetailedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Listing selected = getSelectedListing();
        if (selected == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a listing to add to cart.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (parentPanel == null) {
            JOptionPane.showMessageDialog(this,
                    "Parent buyer panel is not available.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Delegate to BuyerJPanel to manage the shared shopping cart
        parentPanel.addToCart(selected);

        JOptionPane.showMessageDialog(this,
                "Listing added to your shopping cart.",
                "Added",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailed;
    private javax.swing.JButton btnReserch;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblKeyword;
    private javax.swing.JLabel lblPriceRange;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTextField txtHighPrice;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JTextField txtLowPrice;
    // End of variables declaration//GEN-END:variables

    private void populateSortCombo() {
        cmbSort.removeAllItems();
        cmbSort.addItem("Sort by: Default");
        cmbSort.addItem("Price: Low to High");
        cmbSort.addItem("Price: High to Low");
        cmbSort.addItem("Name: A → Z");
        cmbSort.addItem("Name: Z → A");
    }
    
    private void performSearch() {

        String keyword = txtKeyword.getText().trim().toLowerCase();

        double low = 0.0;
        double high = Double.MAX_VALUE;

        try {
            if (!txtLowPrice.getText().trim().isEmpty()) {
                low = Double.parseDouble(txtLowPrice.getText().trim());
            }
            if (!txtHighPrice.getText().trim().isEmpty()) {
                high = Double.parseDouble(txtHighPrice.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Invalid price range.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<Listing> results = new ArrayList<>();

        for (Listing l : allListings) {
            boolean match = true;

            // 1) keyword on title (and optionally description if you have it)
            if (!keyword.isEmpty()) {
                String title = l.getTitle() != null ? l.getTitle().toLowerCase() : "";
                String desc  = l.getDescription() != null ? l.getDescription().toLowerCase() : "";

                if (!title.contains(keyword) && !desc.contains(keyword)) {
                    match = false;
                }
            }

            // 2) price range
            if (l.getPrice() < low || l.getPrice() > high) {
                match = false;
            }

            if (match) {
                results.add(l);
            }
        }

        // sort result then show
        applySort(results);
        refreshTable(results);
    }
    
    private void applySort(List<Listing> list) {
        String sort = cmbSort.getSelectedItem().toString();

        switch (sort) {
            case "Price: Low to High":
                list.sort(Comparator.comparingDouble(Listing::getPrice));
                break;
            case "Price: High to Low":
                list.sort((a, b) -> Double.compare(b.getPrice(), a.getPrice()));
                break;
            case "Name: A → Z":
                list.sort(Comparator.comparing(Listing::getTitle));
                break;
            case "Name: Z → A":
                list.sort((a, b) -> b.getTitle().compareTo(a.getTitle()));
                break;
            default:
                break; // no sort
        }
    }
    
    private void refreshTable(List<Listing> list) {
        DefaultTableModel model = (DefaultTableModel) tblSearchResult.getModel();
        model.setRowCount(0);

        if (list == null) return;

        for (Listing l : list) {
            Object[] row = new Object[]{
                l.getId(),                                   // Listing ID
                l.getTitle(),                                // Name
                String.format("%.2f", l.getPrice()),         // Price
                l.getStatus(),                               // Status
                (l.getSeller() != null
                        ? l.getSeller().getUsername()
                        : "Unknown")                         // Seller
            };
            model.addRow(row);
        }
    }
    
    private Listing getSelectedListing() {
        int row = tblSearchResult.getSelectedRow();
        if (row < 0) {
            return null;
        }

        // Assuming column 0 is "Listing ID"
        String listingId = tblSearchResult.getValueAt(row, 0).toString();

        for (Listing l : allListings) {
            if (l.getId().equals(listingId)) {
                return l;
            }
        }
        return null;
    }
    
}