/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_2.Listing;
import basement_class.UserAccount;
import basement_class.Enterprise_3.WorkRequest.PolicyViolationRequest;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_3.Organization.ContentControlOrganization;
import basement_class.Network;
import basement_class.Organization;
import basement_class.WorkRequest;
import javax.swing.*;

/**
 *
 * @author bob-h
 */
public class ReportViolationWorkArea extends javax.swing.JPanel {

    private final BuyerAccount reporter;        
    private final UserAccount targetUser;       
    private final Listing listing;              
    private final EcoSystem system;
    private final BuyerJPanel parentPanel; 
    
    /**
     * Creates new form ReportViolationWorkArea
     */
    public ReportViolationWorkArea(
            BuyerAccount reporter,
            UserAccount targetUser,
            Listing listing,
            EcoSystem system,
            BuyerJPanel parentPanel) {

        this.reporter = reporter;
        this.targetUser = targetUser;
        this.listing = listing;
        this.system = system;
        this.parentPanel = parentPanel;

        initComponents();
        loadData();
    }
    
    public ReportViolationWorkArea(
            BuyerAccount reporter,
            UserAccount targetUser,
            EcoSystem system,
            BuyerJPanel parentPanel) {

        this(reporter, targetUser, null, system, parentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReporter = new javax.swing.JLabel();
        lblTargetUser = new javax.swing.JLabel();
        lblListing = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtReporter = new javax.swing.JTextField();
        txtTargetUser = new javax.swing.JTextField();
        txtListing = new javax.swing.JTextField();
        txtInfo = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        lblReporter.setText("Reporter");

        lblTargetUser.setText("Target user");

        lblListing.setText("Listing:");

        lblCategory.setText("Category:");

        lblInfo.setText("Info");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "listing_issue", "account_issue", "minor_dispute" }));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReporter)
                        .addGap(40, 40, 40)
                        .addComponent(txtReporter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTargetUser)
                        .addGap(26, 26, 26)
                        .addComponent(txtTargetUser))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblListing)
                        .addGap(50, 50, 50)
                        .addComponent(txtListing))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo)
                            .addComponent(lblCategory))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInfo)
                            .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addContainerGap(866, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReporter)
                    .addComponent(txtReporter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetUser)
                    .addComponent(txtTargetUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListing)
                    .addComponent(txtListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo)
                    .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnBack))
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here
        sendReport();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblListing;
    private javax.swing.JLabel lblReporter;
    private javax.swing.JLabel lblTargetUser;
    private javax.swing.JTextField txtInfo;
    private javax.swing.JTextField txtListing;
    private javax.swing.JTextField txtReporter;
    private javax.swing.JTextField txtTargetUser;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        txtReporter.setText(reporter.getUsername());
        txtTargetUser.setText(targetUser.getUsername());

        if (listing != null) {
            txtListing.setText(listing.getId() + " - " + listing.getTitle());
            txtListing.setEditable(false);
        } else {
            txtListing.setText("N/A");
            txtListing.setEditable(false);
        }
    }
    

    private void sendReport() {

        String category = (String) cmbCategory.getSelectedItem();
        String detail = txtInfo.getText().trim();

        if (detail.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please provide detailed information.",
                    "Missing Info",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        PolicyViolationRequest req = new PolicyViolationRequest(
                reporter,      
                targetUser,    
                listing,       
                category,      
                detail     
        );

        req.setSender(reporter);
        req.setStatus("Pending");

        ContentControlOrganization policyOrg = findPolicyEnforcerOrg(system);

        if (policyOrg == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot find PolicyEnforcer organization. Report failed.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        policyOrg.getWorkRequestDirectory().addWorkRequest(req);


        JOptionPane.showMessageDialog(this,
                "Report submitted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        goBack();
    }

    private void goBack() {
        if (parentPanel != null) {
            parentPanel.showBrowsePanel();  
        }
    }
    
    private ContentControlOrganization findPolicyEnforcerOrg(EcoSystem system) {

        for (Network net : system.getNetworks()) {
            for (Enterprise ent : net.getEnterprises()) {

        
                if (ent.getName().equals("Platform Management")) {

                    for (Organization org : ent.getOrganizations()) {
                        if (org instanceof ContentControlOrganization) {
                            return (ContentControlOrganization) org;
                        }
                    }
                }
            }
        }
        return null;
    }
    
}
