/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import UI.main.LoginPage;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Organization;
import basement_class.UserAccount;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author bob-h
 */
public class TrackJPanel extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private TrackingOrderStatus trackingOrderStatusPanel;
    /**
     * Creates new form TrackJPanel
     */
    public TrackJPanel(BuyerAccount buyerAccount,
                   Organization organization,
                   Enterprise enterprise,
                   EcoSystem system) {

        initComponents();
        this.buyerAccount = buyerAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        initWorkAreaPanels();
    }
    
    private void initWorkAreaPanels() {
        trackingOrderStatusPanel = new TrackingOrderStatus(buyerAccount, system);
        trackWorkArea.add("TRACK_STATUS", trackingOrderStatusPanel);

        CardLayout layout = (CardLayout) trackWorkArea.getLayout();
        layout.show(trackWorkArea, "TRACK_STATUS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnWorkRequestPending = new javax.swing.JButton();
        btnSwitch = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        trackWorkArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(204, 255, 204));
        controlJPanel.setForeground(new java.awt.Color(204, 255, 204));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnWorkRequestPending.setText("Order Pending");
        btnWorkRequestPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkRequestPendingActionPerformed(evt);
            }
        });

        btnSwitch.setText("Switch");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout))
                    .addComponent(btnWorkRequestPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWorkRequestPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );

        jSplitPane1.setLeftComponent(controlJPanel);

        workArea.setLayout(new java.awt.CardLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Tracker Dashboard  ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel1);

        trackWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(trackWorkArea);

        workArea.add(jSplitPane2, "card2");

        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        mainFrame.dispose();

        LoginPage loginPage = new LoginPage(system);
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        if (trackingOrderStatusPanel != null) {
            trackingOrderStatusPanel.refreshData();
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnWorkRequestPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkRequestPendingActionPerformed
        // TODO add your handling code here:
        if (trackingOrderStatusPanel != null) {
            CardLayout layout = (CardLayout) trackWorkArea.getLayout();
            layout.show(trackWorkArea, "TRACK_STATUS");
            trackingOrderStatusPanel.applyFilter("All");
        }
    }//GEN-LAST:event_btnWorkRequestPendingActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
        // Switch back to BuyerJPanel
        BuyerJPanel buyerPanel = new BuyerJPanel(
            buyerAccount, organization, enterprise, system
        );

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.setContentPane(buyerPanel);
            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_btnSwitchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JButton btnWorkRequestPending;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel trackWorkArea;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
