/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.WorkRequest;
import basement_class.WorkRequestDirectory;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_1.WorkRequest.OrderProcessingResultRequest;
import basement_class.Enterprise_2.Listing;
import common_class.Order;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bob-h
 */
public class TrackingOrderStatus extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private EcoSystem system;

    private List<OrderProcessingResultRequest> displayedRequests = new ArrayList<>();


    private String currentFilter = "All";
    /**
     * Creates new form TrackingOrderStatus
     */
    public TrackingOrderStatus() {
        initComponents();
    }
    
    public TrackingOrderStatus(BuyerAccount buyerAccount, EcoSystem system) {
        this(); 
        this.buyerAccount = buyerAccount;
        this.system = system;
        refreshData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblPending = new javax.swing.JLabel();
        lblCompeled = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPending = new javax.swing.JTextField();
        txtCompleted = new javax.swing.JTextField();
        txtCancel = new javax.swing.JTextField();
        lblFilters = new javax.swing.JLabel();
        cmbFilters = new javax.swing.JComboBox<>();
        btnApply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnComplete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        lblTotal.setText("Total:");

        lblPending.setText("Pending:");

        lblCompeled.setText("Completed:");

        lblCancel.setText("Canceled:");

        lblFilters.setText("Filters:");

        btnApply.setText("Apply");

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Title ", "Seller ", "Result ", "Paid"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        btnComplete.setText("Complete");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCompeled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtPending)
                            .addComponent(txtCompleted)
                            .addComponent(txtCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFilters)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btnApply))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilters)
                    .addComponent(cmbFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPending)
                    .addComponent(txtPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompeled)
                    .addComponent(txtCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCancel)
                    .addComponent(txtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplete)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JComboBox<String> cmbFilters;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblCompeled;
    private javax.swing.JLabel lblFilters;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtCancel;
    private javax.swing.JTextField txtCompleted;
    private javax.swing.JTextField txtPending;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public void refreshData() {
        populateTable(currentFilter);
    }
    
    public void applyFilter(String status) {
        if (status == null || status.isEmpty()) {
            status = "All";
        }
        currentFilter = status;
        cmbFilters.setSelectedItem(status);
        populateTable(status);
    }
    
    private List<OrderProcessingResultRequest> loadRequestsForCurrentBuyer() {
        List<OrderProcessingResultRequest> result = new ArrayList<>();

        if (system == null || buyerAccount == null) {
            return result;
        }

        WorkRequestDirectory dir = system.getWorkRequestDirectory();
        if (dir == null) {
            return result;
        }

        for (WorkRequest wr : dir.getRequestsForReceiver(buyerAccount)) {
            if (wr instanceof OrderProcessingResultRequest) {
                result.add((OrderProcessingResultRequest) wr);
            }
        }
        return result;
    }

    /** Populate JTable based on filter */
    private void populateTable(String filterStatus) {
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        displayedRequests.clear();

        List<OrderProcessingResultRequest> all = loadRequestsForCurrentBuyer();

        for (OrderProcessingResultRequest req : all) {

            String status = req.getStatus();

            // Filtering logic
            if (!"All".equalsIgnoreCase(filterStatus)) {
                if (status == null || !filterStatus.equalsIgnoreCase(status)) continue;
            }

            // Get order fields
            Order order = req.getOrder();
            String title = "(unknown)";
            String sellerName = "(unknown)";
            double paid = 0.0;

            if (order != null) {
                paid = order.getTotalPrice();

                // Resolve listing information
                if (system != null &&
                    system.getListingDirectory() != null &&
                    order.getListingId() != null) {

                    Listing listing = system.getListingDirectory()
                                            .findById(order.getListingId());
                    if (listing != null) {
                        if (listing.getTitle() != null)
                            title = listing.getTitle();

                        if (listing.getSeller() != null &&
                            listing.getSeller().getUsername() != null)
                            sellerName = listing.getSeller().getUsername();
                    } else {
                        title = order.getListingId();
                    }
                }
            }

            // Human-friendly result text
            String resultText;
            if (OrderProcessingResultRequest.OP_ACCEPT.equals(req.getOperationType()))
                resultText = "Accepted";
            else if (OrderProcessingResultRequest.OP_REJECT.equals(req.getOperationType()))
                resultText = "Rejected";
            else
                resultText = req.getOperationType();

            Object[] row = new Object[5];
            row[0] = req.getId();
            row[1] = title;
            row[2] = sellerName;
            row[3] = resultText;
            row[4] = paid;

            displayedRequests.add(req);
            model.addRow(row);
        }

        updateSummaryCounts(all);
    }

    /** Update summary counters at the top */
    private void updateSummaryCounts(List<OrderProcessingResultRequest> all) {
        int total = all.size();
        int pending = 0, completed = 0, canceled = 0;

        for (OrderProcessingResultRequest req : all) {
            String status = req.getStatus();
            if (status == null) continue;

            switch (status.toLowerCase()) {
                case "pending": pending++; break;
                case "completed": completed++; break;
                case "canceled": canceled++; break;
            }
        }

        txtTotal.setText(String.valueOf(total));
        txtPending.setText(String.valueOf(pending));
        txtCompleted.setText(String.valueOf(completed));
        txtCancel.setText(String.valueOf(canceled));
    }

    /** Handle Complete button */
    private void handleComplete() {
        int row = tblRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a row first.",
                "No selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderProcessingResultRequest req = displayedRequests.get(row);

        // Invalid status checks
        if ("Completed".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this, "This order is already Completed.");
            return;
        }
        if ("Canceled".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this, "This order has been Canceled.");
            return;
        }
        if (!OrderProcessingResultRequest.OP_ACCEPT.equals(req.getOperationType())) {
            JOptionPane.showMessageDialog(this,
                "Only Accepted requests can be marked as Completed.");
            return;
        }

        // Confirm
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Mark this order as Completed?",
            "Confirm",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        // Update states
        req.setStatus("Completed");
        Order order = req.getOrder();

        if (order != null) {
            order.setStatus(Order.STATUS_COMPLETED);
            if (buyerAccount != null)
                buyerAccount.recordOrder(order.getTotalPrice(), true);
        }

        refreshData();
    }

    /** Handle Cancel button */
    private void handleCancel() {
        int row = tblRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a row first.",
                "No selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderProcessingResultRequest req = displayedRequests.get(row);

        if ("Completed".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this, "Completed orders cannot be canceled.");
            return;
        }
        if ("Canceled".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this, "This order is already Canceled.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Cancel this order? (No points or spending will be counted)",
            "Confirm Cancel",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        req.setStatus("Canceled");

        Order order = req.getOrder();
        if (order != null) {
            order.setStatus(Order.STATUS_CANCELLED);
            if (buyerAccount != null)
                buyerAccount.recordOrder(order.getTotalPrice(), false);
        }

        refreshData();
    }
}