/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise1;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.WorkRequest;
import basement_class.WorkRequestDirectory;
import basement_class.Enterprise_1.Account.BuyerAccount;
import basement_class.Enterprise_1.Organization.OrderSelfTrackerOrganization;
import basement_class.Enterprise_1.WorkRequest.OrderProcessingResultRequest;
import basement_class.Enterprise_2.Listing;
import basement_class.Network;
import basement_class.Organization;
import common_class.Order;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import basement_class.Enterprise_4.OrderReportRequest;
import basement_class.UserAccount;
/**
 *
 * @author bob-h
 */
public class TrackingOrderStatus extends javax.swing.JPanel {

    private BuyerAccount buyerAccount;
    private EcoSystem system;

    // Requests currently displayed in the JTable (one-to-one with rows)
    private List<OrderProcessingResultRequest> displayedRequests = new ArrayList<>();
    
    private String currentFilter = "All";

    /** Constructor used by GUI builder (preview only) */
    public TrackingOrderStatus() {
        initComponents();
        initCustomComponents();
    }

    /** Constructor used at runtime */
    public TrackingOrderStatus(BuyerAccount buyerAccount, EcoSystem system) {
        this();
        this.buyerAccount = buyerAccount;
        this.system = system;
        refreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblPending = new javax.swing.JLabel();
        lblCompeled = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPending = new javax.swing.JTextField();
        txtCompleted = new javax.swing.JTextField();
        txtCancel = new javax.swing.JTextField();
        lblFilters = new javax.swing.JLabel();
        cmbFilters = new javax.swing.JComboBox<>();
        btnApply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnComplete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        lblTotal.setText("Total:");

        lblPending.setText("Pending:");

        lblCompeled.setText("Completed:");

        lblCancel.setText("Canceled:");

        lblFilters.setText("Filters:");

        cmbFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltersActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Title ", "Seller ", "Result ", "Paid"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCompeled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtPending)
                            .addComponent(txtCompleted)
                            .addComponent(txtCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFilters)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btnApply))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReport)))
                        .addContainerGap(600, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilters)
                    .addComponent(cmbFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPending)
                    .addComponent(txtPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompeled)
                    .addComponent(txtCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCancel)
                    .addComponent(txtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplete)
                    .addComponent(btnCancel)
                    .addComponent(btnReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFiltersActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        // Get selected request
        int row = tblRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select an order to report.",
                "No selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderProcessingResultRequest req = displayedRequests.get(row);
        if (req == null) return;

        Order order = req.getOrder();
        if (order == null) {
            JOptionPane.showMessageDialog(this,
                "Order information not available.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get seller (target user to report)
        UserAccount seller = system.getUserAccountDirectory()
            .findByUserId(order.getSellerId());

        if (seller == null) {
            JOptionPane.showMessageDialog(this,
                "Seller information not found.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ask for violation description
        String violationInfo = JOptionPane.showInputDialog(this,
            "Please describe the issue with this order:\n" +
            "Order ID: " + order.getOrderId() + "\n" +
            "Seller: " + seller.getUsername() + "\n\n" +
            "Enter your complaint:",
            "Report Order Issue",
            JOptionPane.QUESTION_MESSAGE);

        // User cancelled
        if (violationInfo == null || violationInfo.trim().isEmpty()) {
            return;
        }

        // Confirm report
        int confirm = JOptionPane.showConfirmDialog(this,
            "Submit this report?\n\n" +
            "Order: " + order.getOrderId() + "\n" +
            "Reporting: " + seller.getUsername() + "\n" +
            "Issue: " + violationInfo.substring(0, Math.min(50, violationInfo.length())) + "...",
            "Confirm Report",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Generate unique request ID
            String reportId = "REPORT-" + java.util.UUID.randomUUID().toString().substring(0, 8);

            // Create OrderReportRequest
            OrderReportRequest reportRequest = new OrderReportRequest(
                order,              // the order being reported
                buyerAccount,       // reporter (buyer)
                seller,             // target user (seller)
                violationInfo       // violation description
            );
            reportRequest.setId(reportId);

            // Find Enterprise 4's Issue Resolution Organization
            boolean sentToIssueResolution = false;

            for (basement_class.Network network : system.getNetworks()) {
                for (basement_class.Enterprise ent : network.getEnterprises()) {
                    // Find Enterprise 4 (Help Center)
                    if (ent.getName().contains("Help Center")) {

                        // Find Issue Resolution Organization
                        for (basement_class.Organization org : ent.getOrganizations()) {
                            if (org.getName().contains("Issue Resolution")) {
                                // Send to organization's work queue
                                org.getWorkRequestDirectory().addWorkRequest(reportRequest);
                                sentToIssueResolution = true;
                                System.out.println("Sent OrderReportRequest to Issue Resolution Organization");
                                break;
                            }
                        }
                    }
                    if (sentToIssueResolution) break;
                }
                if (sentToIssueResolution) break;
            }

            // Also save to system level for tracking
            if (system.getWorkRequestDirectory() != null) {
                system.getWorkRequestDirectory().addWorkRequest(reportRequest);
            }

            if (!sentToIssueResolution) {
                JOptionPane.showMessageDialog(this,
                    "Warning: Issue Resolution Organization not found.\n" +
                    "Report saved to system but may not be processed.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Report submitted successfully!\n\n" +
                    "Report ID: " + reportId + "\n" +
                    "Status: Pending\n\n" +
                    "The Help Center will review your complaint.",
                    "Report Submitted",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to submit report: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox<String> cmbFilters;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblCompeled;
    private javax.swing.JLabel lblFilters;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtCancel;
    private javax.swing.JTextField txtCompleted;
    private javax.swing.JTextField txtPending;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    /** Initialize UI logic after Swing components are created */
    private void initCustomComponents() {
        // Summary fields should not be editable
        txtTotal.setEditable(false);
        txtPending.setEditable(false);
        txtCompleted.setEditable(false);
        txtCancel.setEditable(false);

        // Initialize filter combo box
        cmbFilters.removeAllItems();
        cmbFilters.addItem("All");
        cmbFilters.addItem("Pending");
        cmbFilters.addItem("Completed");
        cmbFilters.addItem("Canceled");

        // Button actions
        btnApply.addActionListener(e -> {
            String selected = (String) cmbFilters.getSelectedItem();
            if (selected == null) selected = "All";
            currentFilter = selected;
            populateTable(currentFilter);
        });

        btnComplete.addActionListener(e -> handleComplete());
        btnCancel.addActionListener(e -> handleCancel());
    }

    /** Public API: refresh using current filter */
    public void refreshData() {
        populateTable(currentFilter);
    }

    /** Public API: set filter then refresh */
    public void applyFilter(String status) {
        if (status == null || status.isEmpty()) status = "All";
        currentFilter = status;
        cmbFilters.setSelectedItem(status);
        populateTable(status);
    }

    /** Get current filter (for outer panels such as TrackJPanel) */
    public String getCurrentFilter() {
        return currentFilter;
    }

    /**
     * Find OrderSelfTrackerOrganization in the ecosystem
     * and return its work request directory.
     */
    private WorkRequestDirectory findTrackerWorkRequestDirectory() {
        if (system == null) return null;

        for (Network n : system.getNetworks()) {
            for (Enterprise e : n.getEnterprises()) {
                for (Organization org : e.getOrganizations()) {
                    if (org instanceof OrderSelfTrackerOrganization) {
                        return org.getWorkRequestDirectory();
                    }
                }
            }
        }
        return null;
    }

    /** Load all result requests where receiver == current buyer */
    private List<OrderProcessingResultRequest> loadRequestsForCurrentBuyer() {
        List<OrderProcessingResultRequest> result = new ArrayList<>();

        if (buyerAccount == null) return result;

        WorkRequestDirectory dir = findTrackerWorkRequestDirectory();
        if (dir == null) return result;

        for (WorkRequest wr : dir.getRequestsForReceiver(buyerAccount)) {
            if (wr instanceof OrderProcessingResultRequest) {
                result.add((OrderProcessingResultRequest) wr);
            }
        }
        return result;
    }

    /** Populate JTable according to filter */
    private void populateTable(String filterStatus) {
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        displayedRequests.clear();

        List<OrderProcessingResultRequest> all = loadRequestsForCurrentBuyer();

        for (OrderProcessingResultRequest req : all) {
            String status = req.getStatus();

            // Filter by status if needed
            if (!"All".equalsIgnoreCase(filterStatus)) {
                if (status == null || !filterStatus.equalsIgnoreCase(status)) {
                    continue;
                }
            }

            Order order = req.getOrder();
            String title = "(unknown)";
            String sellerName = "(unknown)";
            double paid = 0.0;

            if (order != null) {
                paid = order.getTotalPrice();

                if (system != null &&
                    system.getListingDirectory() != null &&
                    order.getListingId() != null) {

                    Listing listing = system.getListingDirectory()
                                           .findById(order.getListingId());
                    if (listing != null) {
                        if (listing.getTitle() != null) {
                            title = listing.getTitle();
                        }
                        if (listing.getSeller() != null &&
                            listing.getSeller().getUsername() != null) {
                            sellerName = listing.getSeller().getUsername();
                        }
                    } else {
                        // fallback: show listingId if listing cannot be found
                        title = order.getListingId();
                    }
                }
            }

            String resultText;
            if (OrderProcessingResultRequest.OP_ACCEPT.equals(req.getOperationType())) {
                resultText = "Accepted";
            } else if (OrderProcessingResultRequest.OP_REJECT.equals(req.getOperationType())) {
                resultText = "Rejected";
            } else {
                resultText = req.getOperationType();
            }

            Object[] row = new Object[5];
            row[0] = req.getId();      // ID
            row[1] = title;            // Title
            row[2] = sellerName;       // Seller
            row[3] = resultText;       // Result (accepted/rejected)
            row[4] = paid;             // Paid amount

            displayedRequests.add(req);
            model.addRow(row);
        }

        updateSummaryCounts(all);
    }

    /** Update Total / Pending / Completed / Canceled fields */
    private void updateSummaryCounts(List<OrderProcessingResultRequest> all) {
        int total = all.size();
        int pending = 0;
        int completed = 0;
        int canceled = 0;

        for (OrderProcessingResultRequest req : all) {
            String status = req.getStatus();
            if (status == null) continue;

            switch (status.toLowerCase()) {
                case "pending":
                    pending++;
                    break;
                case "completed":
                    completed++;
                    break;
                case "canceled":
                    canceled++;
                    break;
                default:
                    break;
            }
        }

        txtTotal.setText(String.valueOf(total));
        txtPending.setText(String.valueOf(pending));
        txtCompleted.setText(String.valueOf(completed));
        txtCancel.setText(String.valueOf(canceled));
    }

    /** Handle Complete button click */
    private void handleComplete() {
        int row = tblRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a row first.",
                    "No selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderProcessingResultRequest req = displayedRequests.get(row);
        if (req == null) return;

        // Status checks
        if ("Completed".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "This order has already been completed.");
            return;
        }
        if ("Canceled".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "This order has been canceled and cannot be completed.");
            return;
        }

        // Only accepted requests can be completed
        if (!OrderProcessingResultRequest.OP_ACCEPT.equals(req.getOperationType())) {
            JOptionPane.showMessageDialog(this,
                    "Only accepted requests can be marked as completed.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Mark this order as Completed?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        // Update request status
        req.setStatus("Completed");

        // Update order and buyer statistics
        Order order = req.getOrder();
        if (order != null) {
            order.setStatus(Order.STATUS_COMPLETED);
            if (buyerAccount != null) {
                buyerAccount.incrementCompletedPurchases();
                buyerAccount.setTotalSpending(buyerAccount.getTotalSpending() + order.getTotalPrice());
                buyerAccount.addPoints((int)(order.getTotalPrice() * 0.05));
            }
        }

        refreshData();
    }

    /** Handle Cancel button click */
    private void handleCancel() {
        int row = tblRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a row first.",
                    "No selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderProcessingResultRequest req = displayedRequests.get(row);
        if (req == null) return;

        if ("Completed".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "Completed orders cannot be canceled.");
            return;
        }
        if ("Canceled".equalsIgnoreCase(req.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "This order is already canceled.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Cancel this order?\nNo points or spending will be counted.",
                "Confirm cancel",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        req.setStatus("Canceled");

        Order order = req.getOrder();
        if (order != null) {
        order.setStatus(Order.STATUS_CANCELLED);

        // Restore listing so that it can be purchased again
        if (system != null &&
            system.getListingDirectory() != null &&
            order.getListingId() != null) {

            Listing listing = system.getListingDirectory()
                                    .findById(order.getListingId());
            if (listing != null) {
                // Make the listing available again for purchase
                listing.setStatus("Approved");
            }
        }

        if (buyerAccount != null) {
            // Canceled order: decrease totalPurchases
            // (because this order was counted when it was created)
            buyerAccount.setTotalPurchases(buyerAccount.getTotalPurchases() - 1);
            double currentBudget = buyerAccount.getProfile().getMaxBudget();
            if (currentBudget > 0) {
                buyerAccount.getProfile().setMaxBudget(currentBudget + order.getTotalPrice());
            }
        }

    refreshData();
    }
    
}
}