/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.main;

import UI.Enterprise3.SuperAdmin;
import basement_class.*;
import javax.swing.*;
import java.awt.*;
import java.util.Locale;

/**
 *
 * @author bob-h
 */
public class LoginPage extends javax.swing.JFrame {
    
    
    private EcoSystem system;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        system = SystemInitializer.initialize();
        initComponents();
    }
    
    public LoginPage(EcoSystem system) {
        this.system = system;   // ✅ 继续用原来的系统
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPage = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnSign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginPage.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblTitle.setText("Campus Marketplace");

        lblSubtitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblSubtitle.setText("Second-Hand Trading Platform");

        lblUser.setText("Username:");

        txtUser.setText("listingmanager1");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        lblPass.setText("Password:");

        txtPass.setText("1234");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSign.setText("Sign up");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
        LoginPage.setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSubtitle)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPageLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTitle)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(LoginPageLayout.createSequentialGroup()
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSign, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LoginPageLayout.createSequentialGroup()
                            .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUser)
                                .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitle)
                .addGap(46, 46, 46)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnSign))
                .addContainerGap(343, Short.MAX_VALUE))
        );

        getContentPane().add(LoginPage, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
//
//    String username = txtUser.getText().trim();
//    String password = txtPass.getText().trim();
//
//    // ===== 1️⃣ 基础校验 =====
//    if (username.isEmpty() || password.isEmpty()) {
//        JOptionPane.showMessageDialog(this, "Please enter username and password");
//        return;
//    }
//
//    UserAccount loginUser = null;
//    Organization userOrg = null;
//    Enterprise userEnterprise = null;
//    
//    
//
//    // =====================================================
//    // ✅ 2️⃣ 超级管理员登录（SystemAdmin → 不走 Organization）
//    // =====================================================
//    loginUser = system.getUserAccountDirectory().findByUsername(username);
//
//    if (loginUser != null 
//        && loginUser.authenticate(password)
//        && loginUser.getRole().getClass().getSimpleName().equals("SystemAdminRole")) {
//
//        loginUser.recordLogin();
//
//        JPanel workArea = new SuperAdmin(system, loginUser);
//
//        this.setContentPane(workArea);
//        this.revalidate();
//        this.repaint();
//
//        JOptionPane.showMessageDialog(workArea,
//            "Welcome System Admin: " + loginUser.getUsername(),
//            "Login Successful",
//            JOptionPane.INFORMATION_MESSAGE);
//        return;
//    }
//
//    // =====================================================
//    // ✅ 3️⃣ 普通用户 & Enterprise 3 管理员（按 Organization 查找）
//    // =====================================================
//    for (Network network : system.getNetworks()) {
//        for (Enterprise enterprise : network.getEnterprises()) {
//            for (Organization org : enterprise.getOrganizations()) {
//
//                UserAccount ua =
//                    org.getUserAccountDirectory().findByUsername(username);
//
//                if (ua != null && ua.authenticate(password)) {
//                    loginUser = ua;
//                    userOrg = org;
//                    userEnterprise = enterprise;
//                    break;
//                }
//            }
//        }
//    }
//
//    // ===== 4️⃣ 登录失败 =====
//    if (loginUser == null) {
//        JOptionPane.showMessageDialog(this,
//            "Invalid username or password",
//            "Login Failed",
//            JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    // ===== 5️⃣ 状态校验 =====
//    if (!loginUser.isActive()) {
//        JOptionPane.showMessageDialog(this,
//            "Your account is currently: " + loginUser.getStatus(),
//            "Account Disabled",
//            JOptionPane.WARNING_MESSAGE);
//        return;
//    }
//
//    // ===== 6️⃣ 记录登录时间 =====
//    loginUser.recordLogin();
//
//    JPanel workArea = null;
//
//    // =====================================================
//    // ✅ Enterprise 1 — Buyer
//    // =====================================================
//    if (loginUser instanceof basement_class.Enterprise_1.Account.BuyerAccount) {
//
//        workArea = new UI.Enterprise1.BuyerJPanel(
//            (basement_class.Enterprise_1.Account.BuyerAccount) loginUser,
//            userOrg,
//            userEnterprise,
//            system
//        );
//    }
//
//    // =====================================================
//    // ✅ Enterprise 2 — Seller
//    // =====================================================
//    else if (loginUser instanceof basement_class.Enterprise_2.Account.SellerAccount) {
//
//        workArea = new UI.Enterprise2.SellerJPanel(
//            (basement_class.Enterprise_2.Account.SellerAccount) loginUser,
//            userOrg,
//            userEnterprise,
//            system
//        );
//    }
//
//    // =====================================================
//    // ✅ ✅ ✅ Enterprise 3 — 所有管理员统一进 AdminJPanel
//    // ✅ ✅ ✅ 后续由 Organization 控制按钮权限
//    // =====================================================
//    else {
//        if (loginUser.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole) {
//
//        for (Network n : system.getNetworks()) {
//            if (!n.getEnterprises().isEmpty()) {
//                userEnterprise = n.getEnterprises().get(0);   // ✅ 你唯一的 Enterprise 3
//                break;
//            }
//        }
//    }
//        
//        workArea = new UI.Enterprise3.AdminJPanel(
//            system,
//            loginUser,
//            userEnterprise,
//            userOrg
//        );
//    }
//
//    // ===== 7️⃣ 防止空跳转 =====
//    if (workArea == null) {
//        JOptionPane.showMessageDialog(this,
//            "No workspace found for your account type",
//            "Configuration Error",
//            JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    // ===== 8️⃣ 切换界面 =====
//    this.setContentPane(workArea);
//    this.revalidate();
//    this.repaint();
//
//    JOptionPane.showMessageDialog(workArea,
//        "Welcome " + loginUser.getUsername() +
//        "\nOrganization: " + (userOrg == null ? "System Admin" : userOrg.getName()),
//        "Login Successful",
//        JOptionPane.INFORMATION_MESSAGE);
//        // =========================================
        // ===============================
    // ✅ 1️⃣ 读取用户名和密码
    // ===============================
    String username = txtUser.getText().trim();
    String password = txtPass.getText().trim();

    // ===============================
    // ✅ 2️⃣ 基础输入校验
    // ===============================
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please enter username and password",
                "Input Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // ===============================
    // ✅ 3️⃣ 准备登录结果变量
    // ===============================
    UserAccount loginUser = null;
    Organization userOrg = null;
    Enterprise userEnterprise = null;

    // ============================================================
    // ✅ 4️⃣ System Admin 登录（不挂 Organization / Enterprise）
    // ============================================================
    loginUser = system.getUserAccountDirectory().findByUsername(username);

    if (loginUser != null
            && loginUser.authenticate(password)
            && loginUser.getRole().getClass().getSimpleName().equals("SystemAdminRole")) {

        loginUser.recordLogin();

        JPanel workArea = new SuperAdmin(system, loginUser);
        this.setContentPane(workArea);
        this.revalidate();
        this.repaint();

        JOptionPane.showMessageDialog(workArea,
                "Welcome System Admin: " + loginUser.getUsername(),
                "Login Successful",
                JOptionPane.INFORMATION_MESSAGE);
        return;   // ✅ System Admin 登录结束
    }

    // ============================================================
    // ✅ 5️⃣ 普通用户 / Enterprise 管理员登录（按 Organization 查找）
    // ============================================================
    for (Network network : system.getNetworks()) {
        for (Enterprise enterprise : network.getEnterprises()) {
            for (Organization org : enterprise.getOrganizations()) {

                UserAccount ua =
                        org.getUserAccountDirectory().findByUsername(username);

                if (ua != null && ua.authenticate(password)) {
                    loginUser = ua;
                    userOrg = org;
                    userEnterprise = enterprise;
                    break;
                }
            }
        }
    }

    // ===============================
    // ✅ 6️⃣ 登录失败校验
    // ===============================
    if (loginUser == null) {
        JOptionPane.showMessageDialog(this,
                "Invalid username or password",
                "Login Failed",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ===============================
    // ✅ 7️⃣ 账号状态校验
    // ===============================
    if (!loginUser.isActive()) {
        JOptionPane.showMessageDialog(this,
                "Your account is currently: " + loginUser.getStatus(),
                "Account Disabled",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // ===============================
    // ✅ 8️⃣ 记录最后登录时间
    // ===============================
    loginUser.recordLogin();

    JPanel workArea = null;

    // ============================================================
    // ✅ ✅ ✅ Enterprise 1 — Buyer（✅ 预留）
    // ============================================================
    if (loginUser instanceof basement_class.Enterprise_1.Account.BuyerAccount) {

        // TODO: Enterprise 1 买家界面跳转逻辑
        // workArea = new UI.Enterprise1.BuyerJPanel(...);
    }

    // ============================================================
    // ✅ ✅ ✅ Enterprise 2 — Seller（✅ 预留）
    // ============================================================
    else if (loginUser instanceof basement_class.Enterprise_2.Account.SellerAccount) {

        // TODO: Enterprise 2 卖家界面跳转逻辑
        // workArea = new UI.Enterprise2.SellerJPanel(...);
    }

    // ============================================================
    // ✅ ✅ ✅ Enterprise 3 — Platform Management（✅ 已实现）
    // ============================================================
    else {

        // ✅ 确保拿到 Enterprise 3
        if (userEnterprise == null && loginUser.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole) {
            for (Network n : system.getNetworks()) {
        for (Enterprise e : n.getEnterprises()) {
        if ("Platform Management".equals(e.getName())) {
            userEnterprise = e;
            break;
        }
    }
            }
        }

        workArea = new UI.Enterprise3.AdminJPanel(
                system,
                loginUser,
                userEnterprise,
                userOrg
        );
    }

    // ============================================================
    // ✅ ✅ ✅ Enterprise 4 — （✅ 预留）
    // ============================================================
    // else if (loginUser instanceof basement_class.Enterprise_4.Account.XXXAccount) {
    //     TODO: Enterprise 4 跳转逻辑
    // }

    // ===============================
    // ✅ 9️⃣ 防止空跳转
    // ===============================
    if (workArea == null) {
        JOptionPane.showMessageDialog(this,
                "No workspace found for your account type",
                "Configuration Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ===============================
    // ✅ 🔟 正式切换页面
    // ===============================
    this.setContentPane(workArea);
    this.revalidate();
    this.repaint();

    JOptionPane.showMessageDialog(workArea,
            "Welcome " + loginUser.getUsername()
            + "\nOrganization: " + (userOrg == null ? "System Admin" : userOrg.getName()),
            "Login Successful",
            JOptionPane.INFORMATION_MESSAGE);
    
 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Locale.setDefault(Locale.US);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSign;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    /**
    * Find the organization that the user belongs to
    * @param user The user account
    * @param system The ecosystem instance
    * @return Organization or null if not found
    */
   private Organization findUserOrganization(UserAccount user, EcoSystem system) {
       for (Network network : system.getNetworks()) {
           for (Enterprise enterprise : network.getEnterprises()) {
               for (Organization org : enterprise.getOrganizations()) {
                   UserAccount found = org.getUserAccountDirectory()
                       .findByUserId(user.getUserId());
                   if (found != null) {
                       return org;
                   }
               }
           }
       }
       return null;
   }

   /**
    * Find the enterprise that contains the given organization
    * @param organization The organization
    * @param system The ecosystem instance
    * @return Enterprise or null if not found
    */
   private Enterprise findUserEnterprise(Organization organization, EcoSystem system) {
       if (organization == null) {
           return null;
       }

       for (Network network : system.getNetworks()) {
           for (Enterprise enterprise : network.getEnterprises()) {
               if (enterprise.getOrganizations().contains(organization)) {
                   return enterprise;
               }
           }
       }
       return null;
   }

 
    
}
