/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise4;

import basement_class.Enterprise_4.Message;
import basement_class.Enterprise_4.MessageDirectory;
import basement_class.Enterprise_4.MessageFlagRequest;
import basement_class.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author yujie-liang
 */
public class BuyerSellerChatPanel extends javax.swing.JPanel {
    private final UserAccount currentUser;      
    private final ArrayList<UserAccount> partners;   
    private final MessageDirectory messageDirectory;

    /**
     * Creates new form BuyerSellerChatPanel
     */
    public BuyerSellerChatPanel(UserAccount currentUser,
                                ArrayList<UserAccount> partners,
                                MessageDirectory messageDirectory) {
        this.currentUser = currentUser;
        this.partners = partners;
        this.messageDirectory = messageDirectory;

        initComponents();
        for (UserAccount ua : partners) {
            cbChatPartner.addItem(ua);
        }
        reloadConversation();
        reloadReportCombo();
    }
    private void reloadConversation() {
        taConversation.setText("");

        UserAccount partner = (UserAccount) cbChatPartner.getSelectedItem();
        if (partner == null) return;

        ArrayList<Message> list = messageDirectory.getMessagesBetween(currentUser, partner);
        for (Message m : list) {
            appendMessageToConversation(m);
        }
    }
   
   
    private void reloadReportCombo() {
        cbMessageToReport.removeAllItems();

        UserAccount partner = (UserAccount) cbChatPartner.getSelectedItem();
        if (partner == null) return;

        ArrayList<Message> list = messageDirectory.getMessagesBetween(currentUser, partner);
        for (Message m : list) {
            // Only allow the current user to report the message "sent by the other party"
            if (!m.getSender().equals(currentUser)) {
                cbMessageToReport.addItem(m);
            }
        }
    }
    private void appendMessageToConversation(Message m) {
        if (m == null) return;
        String senderName = (m.getSender() != null) ? m.getSender().getUsername() : "Unknown";
        taConversation.append(senderName + ": " + m.getContent() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbChatPartner = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taConversation = new javax.swing.JTextArea();
        tfMessageInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        cbMessageToReport = new javax.swing.JComboBox<>();
        tfReportReason = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();

        cbChatPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChatPartnerActionPerformed(evt);
            }
        });

        taConversation.setColumns(20);
        taConversation.setRows(5);
        jScrollPane1.setViewportView(taConversation);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(cbChatPartner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMessageInput)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMessageToReport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfReportReason)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(cbChatPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cbMessageToReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfReportReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnReport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMessageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        UserAccount partner = (UserAccount) cbChatPartner.getSelectedItem();
        if (partner == null) {
            JOptionPane.showMessageDialog(this, "Please select a chat partner.");
            return;
             }

        String text = tfMessageInput.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Message cannot be empty.");
            return;
        }

        Message msg = messageDirectory.addMessage(currentUser, partner, text);

        // update message to chat area
        if (msg != null) {
            appendMessageToConversation(msg);
        }

        tfMessageInput.setText("");
        reloadReportCombo(); 
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        Message selectedMessage = (Message) cbMessageToReport.getSelectedItem();
        if (selectedMessage == null) {
            JOptionPane.showMessageDialog(this, "Please select a message to report.");
            return;
        }

        String reason = tfReportReason.getText().trim();
        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a reason for the report.");
            return;
        }

        
        selectedMessage.flagByUser();

        MessageFlagRequest req = new MessageFlagRequest(selectedMessage, currentUser, reason);
        // someOrganization.getWorkRequestDirectory().addRequest(req);

        JOptionPane.showMessageDialog(this, "Report submitted. Thank you.");

        tfReportReason.setText("");
    }//GEN-LAST:event_btnReportActionPerformed

    private void cbChatPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChatPartnerActionPerformed
        // TODO add your handling code here:
        reloadConversation();
        reloadReportCombo();
    }//GEN-LAST:event_cbChatPartnerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox<UserAccount> cbChatPartner;
    private javax.swing.JComboBox<Message> cbMessageToReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taConversation;
    private javax.swing.JTextField tfMessageInput;
    private javax.swing.JTextField tfReportReason;
    // End of variables declaration//GEN-END:variables
}
