/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise4;

import basement_class.Enterprise_4.Message;
import basement_class.Enterprise_4.MessageDirectory;
import basement_class.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author yujie-liang
 */
public class BuyerSellerMonitorPanel extends javax.swing.JPanel {

    private ArrayList<UserAccount> buyers;
    private ArrayList<UserAccount> sellers;
    private MessageDirectory messageDirectory;
    /**
     * Creates new form BuyerSellerMonitorPanel
     */
    public BuyerSellerMonitorPanel(ArrayList<UserAccount> buyers, ArrayList<UserAccount> sellers, MessageDirectory messageDirectory) {
        this.buyers = buyers;
        this.sellers = sellers;
        this.messageDirectory = messageDirectory;

        initComponents();
        // Initialize two combox
        for (UserAccount b : buyers) {
            cbBuyer.addItem(b);
        }

        for (UserAccount s : sellers) {
            cbSeller.addItem(s);
        }

        reloadConversation();
        reloadFlagCombo();
    }
    
     private void reloadConversation() {
        taConversation.setText("");

        UserAccount buyer = (UserAccount) cbBuyer.getSelectedItem();
        UserAccount seller = (UserAccount) cbSeller.getSelectedItem();
        if (buyer == null || seller == null) return;

        ArrayList<Message> messages = messageDirectory.getMessagesBetween(buyer, seller);
        for (Message m : messages) {
            appendMessageToConversation(m);
        }
    }
     
    private void appendMessageToConversation(Message m) {
        if (m == null) return;
        String senderName = (m.getSender() != null) ? m.getSender().getUsername() : "Unknown";
        taConversation.append(senderName + ": " + m.getContent() + "\n");
    }
    
    private void reloadFlagCombo() {
        cbMessageToFlag.removeAllItems();

        UserAccount buyer = (UserAccount) cbBuyer.getSelectedItem();
        UserAccount seller = (UserAccount) cbSeller.getSelectedItem();
        if (buyer == null || seller == null) return;

        ArrayList<Message> messages = messageDirectory.getMessagesBetween(buyer, seller);
        for (Message msg : messages) {
            cbMessageToFlag.addItem(msg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBuyer = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taConversation = new javax.swing.JTextArea();
        cbMessageToFlag = new javax.swing.JComboBox<>();
        cbSeller = new javax.swing.JComboBox<>();
        btnFlag = new javax.swing.JButton();

        cbBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuyerActionPerformed(evt);
            }
        });

        taConversation.setColumns(20);
        taConversation.setRows(5);
        jScrollPane1.setViewportView(taConversation);

        cbSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSellerActionPerformed(evt);
            }
        });

        btnFlag.setText("Flag");
        btnFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(cbBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMessageToFlag, 0, 200, Short.MAX_VALUE)
                            .addComponent(btnFlag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cbBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMessageToFlag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFlag)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuyerActionPerformed
        // TODO add your handling code here:
        reloadConversation();
        reloadFlagCombo();
    }//GEN-LAST:event_cbBuyerActionPerformed

    private void cbSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSellerActionPerformed
        // TODO add your handling code here:
        reloadConversation();
        reloadFlagCombo();
    }//GEN-LAST:event_cbSellerActionPerformed

    private void btnFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlagActionPerformed
        // TODO add your handling code here:
        Message selected = (Message) cbMessageToFlag.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a message to flag.");
            return;
        }

        // If it has already been marked, it will not be marked again

        Boolean alreadyFlagged = selected.isIsFlagged();
        if (alreadyFlagged) {
            JOptionPane.showMessageDialog(this, "This message has already been flagged.");
            return;
        }

        //Mark the message
        selected.contentIsInappropriate();   // 标记 isFlagged = true（根据你的实现）

        reloadConversation();
        reloadFlagCombo();

        JOptionPane.showMessageDialog(this, "Message flagged and masked as \"******\".");
    }//GEN-LAST:event_btnFlagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlag;
    private javax.swing.JComboBox<UserAccount> cbBuyer;
    private javax.swing.JComboBox<Message> cbMessageToFlag;
    private javax.swing.JComboBox<UserAccount> cbSeller;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taConversation;
    // End of variables declaration//GEN-END:variables
}
