/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise4;

import basement_class.Enterprise_4.CommunicationServiceOrganization;
import basement_class.Enterprise_4.Message;
import basement_class.Enterprise_4.MessageFlagRequest;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yujie-liang
 */
public class MessageFlagHandlingPanel extends javax.swing.JPanel {
    private CommunicationServiceOrganization communicationServiceOrg;
    private ArrayList<MessageFlagRequest> requestList;

    /**
     * Creates new form MessageFlagHandlingPanel
     */
    public MessageFlagHandlingPanel(CommunicationServiceOrganization communicationServiceOrg) {
        this.communicationServiceOrg = communicationServiceOrg;
        this.requestList = new ArrayList<>();

        initComponents();

        reloadRequests();
    }
    private void reloadRequests() {
        requestList.clear();
        DefaultTableModel tableModel = (DefaultTableModel) tblRequests.getModel();
        tableModel.setRowCount(0);

        if (communicationServiceOrg == null
                || communicationServiceOrg.getWorkRequestDirectory() == null) {
            return;
        }

        for (WorkRequest wr : communicationServiceOrg.getWorkRequestDirectory().getRequestList()) {
            if (wr instanceof MessageFlagRequest) {
                MessageFlagRequest mfr = (MessageFlagRequest) wr;
                requestList.add(mfr);

                String id = mfr.getId();
                UserAccount reporter = mfr.getSender();
                String reporterName = (reporter != null) ? reporter.getUsername() : "Unknown";

                Message msg = mfr.getFlaggedMessage();
                
                String msgPreview = msg.getContent();

                String reason = mfr.getReason();
                
                String status = mfr.getStatus();

                tableModel.addRow(new Object[]{id, reporterName, msgPreview, reason, status});
            }
        }

        tfMessageDetail.setText("");
        tfReasonDetail.setText("");
        btnApprove.setEnabled(false);
        btnReject.setEnabled(false);
    }
    
    private void onTableSelectionChanged() {
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            tfMessageDetail.setText("");
            tfReasonDetail.setText("");
            btnApprove.setEnabled(false);
            btnReject.setEnabled(false);
            return;
        }

        MessageFlagRequest req = requestList.get(row);

        // show detail on textfiled
        Message msg = req.getFlaggedMessage();
        tfMessageDetail.setText(msg != null ? msg.getContent() : "");
        tfReasonDetail.setText(req.getReason() != null ? req.getReason() : "");

        // Determine whether the button is available based on its status
        String status = req.getStatus();
        if (status.equalsIgnoreCase("Pending")) {
            btnApprove.setEnabled(true);
            btnReject.setEnabled(true);
        } else {
            btnApprove.setEnabled(false);
            btnReject.setEnabled(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        tfMessageDetail = new javax.swing.JTextField();
        tfReasonDetail = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Reporter", "Message", "Reason", "Status"
            }
        ));
        tblRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRequests);

        tfMessageDetail.setEditable(false);

        tfReasonDetail.setEditable(false);

        btnApprove.setText("Approve");
        btnApprove.setEnabled(false);
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.setEnabled(false);
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(tfMessageDetail)
                            .addComponent(tfReasonDetail))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfMessageDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfReasonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }

        MessageFlagRequest req = requestList.get(row);

        // Only pending can be processed
        if (req.getStatus() != null && !req.getStatus().equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "This request is already processed.");
            return;
        }

        //marked message
        Message msg = req.getFlaggedMessage();
        if (msg != null) {
            msg.contentIsInappropriate();
        }

        // update request status
        req.setStatus("Approved");

        JOptionPane.showMessageDialog(this, "Request approved.");

        reloadRequests();

    
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }

        MessageFlagRequest req = requestList.get(row);

        if (req.getStatus() != null && !req.getStatus().equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "This request is already processed.");
            return;
        }

        req.setStatus("Rejected");

        JOptionPane.showMessageDialog(this, "Request rejected.");

        reloadRequests();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void tblRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestsMouseClicked
        // TODO add your handling code here:
        onTableSelectionChanged();
    }//GEN-LAST:event_tblRequestsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextField tfMessageDetail;
    private javax.swing.JTextField tfReasonDetail;
    // End of variables declaration//GEN-END:variables
}
