/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise4;

import basement_class.Enterprise_4.IssueResolutionOrganization;
import basement_class.Enterprise_4.OrderReportRequest;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import common_class.Order;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yujie-liang
 */
public class OrderReportHandlingPanel extends javax.swing.JPanel {
    private IssueResolutionOrganization issueResolutionOrg;          

    private ArrayList<OrderReportRequest> requestList;

    /**
     * Creates new form OrderReportHandlingPanel
     */
   public OrderReportHandlingPanel(IssueResolutionOrganization issueResolutionOrg) {
        this.issueResolutionOrg = issueResolutionOrg;
        this.requestList = new ArrayList<>();

        reloadRequests();
    }
   
   private void reloadRequests() {
        requestList.clear();
        DefaultTableModel tableModel = (DefaultTableModel) tblRequests.getModel();
        tableModel.setRowCount(0);

        if (issueResolutionOrg == null || issueResolutionOrg.getWorkRequestDirectory() == null) {
            return;
        }

        for (WorkRequest wr : issueResolutionOrg.getWorkRequestDirectory().getRequestList()) {
            if (wr instanceof OrderReportRequest) {
                OrderReportRequest orr = (OrderReportRequest) wr;
                requestList.add(orr);

                String id = orr.getId();
                UserAccount reporter = orr.getReporter();
                String reporterName = reporter != null ? reporter.getUsername() : "Unknown";

                String orderSummary = "";
                Order order = orr.getOrder(); 
                if (order != null) {
                    orderSummary = "Order#" + order.getOrderId();
                }

                String ViolationInfo = orr.getViolationInfo();
                String status = orr.getStatus();

                tableModel.addRow(new Object[] { id, reporterName, orderSummary, ViolationInfo, status });
            }
        }

        taOrderDetail.setText("");
        tfHandleReason.setText("");
        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);
    }
   
    private void onTableSelectionChanged() {
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            taOrderDetail.setText("");
            tfHandleReason.setText("");
            btnAccept.setEnabled(false);
            btnReject.setEnabled(false);
            return;
        }

        OrderReportRequest req = requestList.get(row);

        // 显示订单详细信息
        taOrderDetail.setText(buildOrderDetail(req));

        String status = req.getStatus();
        if (status == null || status.equalsIgnoreCase("Pending")) {
            btnAccept.setEnabled(true);
            btnReject.setEnabled(true);
        } else {
            btnAccept.setEnabled(false);
            btnReject.setEnabled(false);
        }
    }
    private String buildOrderDetail(OrderReportRequest req) {
        Order order = req.getOrder();
        if (order == null) {
            return "No order information.";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Order ID: ").append(order.getOrderId()).append(" ");
        sb.append("Listing ID: ").append(order.getListingId()).append(" ");
        sb.append("Buyer ID: ").append(order.getBuyerId()).append(" ");
        sb.append("Seller ID: ").append(order.getSellerId()).append(" ");
        sb.append("Total Price: ").append(order.getTotalPrice()).append(" ");
        sb.append("Order Status: ").append(order.getStatus()).append(" ");

        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOrderDetail = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfHandleReason = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Reporter", "Order", "ViolationInfo", "Status"
            }
        ));
        tblRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRequests);

        taOrderDetail.setColumns(20);
        taOrderDetail.setRows(5);
        jScrollPane2.setViewportView(taOrderDetail);

        jLabel1.setText("Detail");

        jLabel2.setText("Reason");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jLabel3.setText("Order Report Handing");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfHandleReason))
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHandleReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }

        OrderReportRequest req = requestList.get(row);

        if (req.getStatus() != null && !req.getStatus().equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "This request has already been processed.");
            return;
        }

        String handleReason = tfHandleReason.getText().trim();
        if (handleReason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a handle reason.");
            return;
        }

        Order order = req.getOrder();
        if (order != null) {
            order.setStatus("Cancelled");
        }

        req.setReason(handleReason);

        req.setStatus("Approved");

        JOptionPane.showMessageDialog(this, "Order report accepted. Order has been cancelled.");

        reloadRequests();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if (row < 0 || row >= requestList.size()) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }

        OrderReportRequest req = requestList.get(row);

        if (req.getStatus() != null && !req.getStatus().equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "This request has already been processed.");
            return;
        }

        String handleReason = tfHandleReason.getText().trim();
        if (handleReason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a handle reason.");
            return;
        }

        req.setReason(handleReason);
        req.setStatus("Rejected");

        JOptionPane.showMessageDialog(this, "Order report rejected.");

        reloadRequests();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void tblRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestsMouseClicked
        // TODO add your handling code here:
        onTableSelectionChanged();
    }//GEN-LAST:event_tblRequestsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taOrderDetail;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextField tfHandleReason;
    // End of variables declaration//GEN-END:variables
}
