/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import UI.main.LoginPage;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_3.Organization.ContentControlOrganization;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Organization;
import basement_class.UserAccount;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class AdminJPanel extends javax.swing.JPanel {
    private EcoSystem system;
    private UserAccount adminUser;
    private Enterprise enterprise;
    private Organization userOrg;
    /**
     * Creates new form AccountAdminWorkAreaPanel
     */
    public AdminJPanel(EcoSystem system,UserAccount adminUser,Enterprise enterprise,Organization userOrg) {
        initComponents();
        this.system=system;
        this.adminUser=adminUser;
        this.enterprise=enterprise;
        this.userOrg=userOrg;

        System.out.println("====== AdminJPanel Debug ======");
    System.out.println("Username: " + adminUser.getUsername());
    System.out.println("Role: " + adminUser.getRole().getClass().getName());
    System.out.println("RoleName: " + adminUser.getRole().getRoleName());
    System.out.println("Organization: " + (userOrg == null ? "NULL" : userOrg.getName()));
    System.out.println("================================");
        
//        FakeDataGenerator.generate(system, enterprise);
        configureButtonByOrganization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnAccountManagement = new javax.swing.JButton();
        btnRegistrationReview = new javax.swing.JButton();
        btnContentModeration = new javax.swing.JButton();
        btnPolicyEnforcement = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        workProcessJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlJPanel.setBackground(new java.awt.Color(102, 255, 255));
        controlJPanel.setForeground(new java.awt.Color(102, 255, 255));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAccountManagement.setText("Acoount Management");
        btnAccountManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManagementActionPerformed(evt);
            }
        });

        btnRegistrationReview.setText("Registration Review");
        btnRegistrationReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationReviewActionPerformed(evt);
            }
        });

        btnContentModeration.setText("Content Moderation");
        btnContentModeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContentModerationActionPerformed(evt);
            }
        });

        btnPolicyEnforcement.setText("Policy Enforcement");
        btnPolicyEnforcement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyEnforcementActionPerformed(evt);
            }
        });

        btnHistory.setText("History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrationReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContentModeration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPolicyEnforcement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout))
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAccountManagement)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrationReview)
                .addGap(18, 18, 18)
                .addComponent(btnContentModeration)
                .addGap(18, 18, 18)
                .addComponent(btnPolicyEnforcement)
                .addGap(18, 18, 18)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );

        jSplitPane1.setLeftComponent(controlJPanel);

        javax.swing.GroupLayout workProcessJPanelLayout = new javax.swing.GroupLayout(workProcessJPanel);
        workProcessJPanel.setLayout(workProcessJPanelLayout);
        workProcessJPanelLayout.setHorizontalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
        );
        workProcessJPanelLayout.setVerticalGroup(
            workProcessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workProcessJPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManagementActionPerformed
        UserControlOrganization org =
        (UserControlOrganization) enterprise.getOrganizationByName("User Control");

        AccountAdminWorkAreaPanel panel =
        new AccountAdminWorkAreaPanel(system, adminUser, org);

        replaceWorkArea(panel); 
    }//GEN-LAST:event_btnAccountManagementActionPerformed

    private void btnRegistrationReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationReviewActionPerformed
        // TODO add your handling code here:
         UserControlOrganization org =
        (UserControlOrganization) enterprise.getOrganizationByName("User Control");

        RegistrationReviewJPanel panel =
        new RegistrationReviewJPanel(
            adminUser,
            org,
            enterprise,
            system
        );

        replaceWorkArea(panel);
    }//GEN-LAST:event_btnRegistrationReviewActionPerformed

    private void btnContentModerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContentModerationActionPerformed
        // TODO add your handling code here:
        ContentControlOrganization org =
        (ContentControlOrganization) enterprise.getOrganizationByName("Content Control");

        ContentModerationJpanel panel =
        new ContentModerationJpanel(system, adminUser, org);
        replaceWorkArea(panel);
    }//GEN-LAST:event_btnContentModerationActionPerformed

    private void btnPolicyEnforcementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyEnforcementActionPerformed
        // TODO add your handling code here:
        ContentControlOrganization org =
        (ContentControlOrganization) enterprise.getOrganizationByName("Content Control");

        PolicyEnforcementJPanel panel =
        new PolicyEnforcementJPanel(system, adminUser, org);
        replaceWorkArea(panel);
    }//GEN-LAST:event_btnPolicyEnforcementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // ✅ 2️⃣ 销毁旧窗口（只销毁 UI）
    mainFrame.dispose();

    // ✅ 3️⃣ 用【同一个 system】重新打开 Login
    LoginPage loginPage = new LoginPage(system);  // ✅ 核心就在这一句！
    loginPage.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
     
        UserControlOrganization org =
        (UserControlOrganization) enterprise.getOrganizationByName("User Control");


        HistoryPanel panel = new HistoryPanel(system, adminUser, org);

        replaceWorkArea(panel);
    }//GEN-LAST:event_btnHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManagement;
    private javax.swing.JButton btnContentModeration;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPolicyEnforcement;
    private javax.swing.JButton btnRegistrationReview;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workProcessJPanel;
    // End of variables declaration//GEN-END:variables
    private void replaceWorkArea(JPanel panel) {
        workProcessJPanel.removeAll();
        workProcessJPanel.setLayout(new java.awt.BorderLayout());
        workProcessJPanel.add(panel, java.awt.BorderLayout.CENTER);
        workProcessJPanel.revalidate();
        workProcessJPanel.repaint();
    }
private void configureButtonByOrganization() {

    // ✅ 默认全部隐藏
    btnAccountManagement.setVisible(false);
    btnRegistrationReview.setVisible(false);
    btnContentModeration.setVisible(false);
    btnPolicyEnforcement.setVisible(false);
    btnHistory.setVisible(false);

    // ✅ 超级管理员（SystemAdmin） → 不绑定 organization → 全开
    if (adminUser.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole) {
        btnAccountManagement.setVisible(true);
        btnRegistrationReview.setVisible(true);
        btnContentModeration.setVisible(true);
        btnPolicyEnforcement.setVisible(true);
        btnHistory.setVisible(true);
        return;
    }

    // ✅ 账号管理组织
    if (userOrg instanceof UserControlOrganization) {
        btnAccountManagement.setVisible(true);
        btnRegistrationReview.setVisible(true);
        btnHistory.setVisible(true);
        return;
    }

    // ✅ 内容 + 违规组织
    if (userOrg instanceof ContentControlOrganization) {
        btnContentModeration.setVisible(true);
        btnPolicyEnforcement.setVisible(true);
        btnHistory.setVisible(true);
        return;
    }
}
}
