/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.WorkRequest.AccountStatusReviewRequest;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.E3.UserManagementService;

/**
 *
 * @author Linyiyang
 */
public class HistoryPanel extends javax.swing.JPanel {
    private EcoSystem system;
    private UserAccount admin;
    private UserControlOrganization userOrg;
        
    
    /**
     * Creates new form AccountAdminWorkAreaPanel
     */
    public HistoryPanel(EcoSystem system,UserAccount admin,UserControlOrganization org) {
        initComponents();
        this.system=system;
        this.admin=admin;
        this.userOrg = org;
        loadTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnDescpriton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchByID = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        btnSearchByRequestID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSearchByType = new javax.swing.JButton();
        fieldType = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Manager", "Action", "Type", "null"
            }
        ));
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(4).setMinWidth(0);
            tblUser.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblUser.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnDescpriton.setText("Descpriton");
        btnDescpriton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescpritonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("History");

        SearchByID.setText("Search by ID:");

        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });

        btnSearchByRequestID.setText("Search");
        btnSearchByRequestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByRequestIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Search by Type");

        btnSearchByType.setText("Search");
        btnSearchByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByTypeActionPerformed(evt);
            }
        });

        fieldType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchByID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByRequestID)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btnDescpriton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchByID)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByRequestID)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnSearchByType)
                    .addComponent(fieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDescpriton)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescpritonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescpritonActionPerformed
         int row = tblUser.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a record first.");
        return;
    }

    WorkRequest req = (WorkRequest) tblUser.getValueAt(row, 4);

    String comment = req.getReviewComment();
    if (comment == null || comment.isBlank()) {
        comment = "(No comment)";
    }

    String msg = """
        Request ID: %s
        Reviewer: %s
        Type: %s
        Action: %s
        Time: %s

        Comment:
        %s
        """.formatted(
            req.getId(),
            req.getReviewer() == null ? "N/A" : req.getReviewer().getUsername(),
            getRequestType(req),
            req.getReviewAction(),
            req.getResolveDate(),
            comment
    );

    JOptionPane.showMessageDialog(this, msg, "History Detail", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDescpritonActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void btnSearchByRequestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByRequestIDActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
model.setRowCount(0);

boolean found = false;

boolean isSystemAdmin =
        admin.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole;

String keyword = fieldID.getText().trim();

for (Network n : system.getNetworks()) {
    for (Enterprise e : n.getEnterprises()) {
        for (Organization org : e.getOrganizations()) {
            for (WorkRequest req : org.getWorkRequestDirectory().getRequestList()) {

                if (!req.isResolved()) continue;
                if (req.getId() == null) continue;

                boolean canSee =
                        isSystemAdmin  ||
                        (req.getReviewer() != null && req.getReviewer().equals(admin));

                if (canSee && req.getId().equalsIgnoreCase(keyword)) {
                    addRow(req, model);
                    found = true;
                }
            }
        }
    }
}

if (!found) {
    JOptionPane.showMessageDialog(this, "No matching record found.");
}
    }//GEN-LAST:event_btnSearchByRequestIDActionPerformed

    private void fieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTypeActionPerformed

    private void btnSearchByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByTypeActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
model.setRowCount(0);

boolean found = false;

boolean isSystemAdmin =
        admin.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole;

String keyword = fieldType.getText().trim().toLowerCase();

for (Network n : system.getNetworks()) {
    for (Enterprise e : n.getEnterprises()) {
        for (Organization org : e.getOrganizations()) {
            for (WorkRequest req : org.getWorkRequestDirectory().getRequestList()) {

                if (!req.isResolved()) continue;

                boolean canSee =
                        isSystemAdmin ||
                        (req.getReviewer() != null && req.getReviewer().equals(admin));

                if (!canSee) continue;

                String type = getRequestType(req).toLowerCase();
                if (type.contains(keyword)) {
                    addRow(req, model);
                    found = true;
                }
            }
        }
    }
}

if (!found) {
    JOptionPane.showMessageDialog(this, "No matching record found.");
}
    }//GEN-LAST:event_btnSearchByTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchByID;
    private javax.swing.JButton btnDescpriton;
    private javax.swing.JButton btnSearchByRequestID;
    private javax.swing.JButton btnSearchByType;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
          DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
    model.setRowCount(0);

boolean isSystemAdmin =
        admin.getRole() instanceof basement_class.Enterprise_3.Role.SystemAdminRole;

   
    for (Network n : system.getNetworks()) {
        for (Enterprise e : n.getEnterprises()) {
            for (Organization org : e.getOrganizations()) {
                for (WorkRequest req : org.getWorkRequestDirectory().getRequestList()) {

                  
                  if (isSystemAdmin) {
    if (req.isResolved()) {
        addRow(req, model);   
    }
} else {
    if (req.isResolved()
            && req.getReviewer() != null
            && req.getReviewer().equals(admin)) {

        addRow(req, model);  
    }
}
                }
            }
        }
    }
    }  

    private void addRow(WorkRequest req, DefaultTableModel model) {

    Object[] row = new Object[5];

    row[0] = req.getId();  // ✅ Request ID

    row[1] = (req.getReviewer() == null)
            ? "N/A"
            : req.getReviewer().getUsername();  

    row[2] = req.getReviewAction();            

    row[3] = getRequestType(req);              

    row[4] = req;                             

    model.addRow(row);
}

private String getRequestType(WorkRequest req) {

    if (req instanceof basement_class.Enterprise_3.WorkRequest.RegistrationApprovalRequest)
        return "Registration";

    if (req instanceof basement_class.Enterprise_3.WorkRequest.AccountStatusReviewRequest)
        return "Account Status";

    if (req instanceof basement_class.Enterprise_3.WorkRequest.ListingReviewRequest)
        return "Listing Review";

    if (req instanceof basement_class.Enterprise_3.WorkRequest.PolicyViolationRequest)
        return "Policy Violation";

    return "Unknown";
}
}
