/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import basement_class.DAO.UserAccountDAO;
import basement_class.DAO.UserAccountFileDAO;
import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_3.Account.PlatformAdminAccount;
import basement_class.Enterprise_3.Organization.ContentControlOrganization;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.Role.AccountAdminRole;
import basement_class.Enterprise_3.Role.ContentModeratorRole;
import basement_class.Enterprise_3.WorkRequest.AccountStatusReviewRequest;
import basement_class.Network;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Window;
import java.util.UUID;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import service.E3.UserManagementService;

/**
 *
 * @author Linyiyang
 */
public class PlantformManagmentJPanel extends javax.swing.JPanel {
    private EcoSystem system;
    private UserAccount admin;
    private UserControlOrganization userOrg;
    /**
     * Creates new form AccountAdminWorkAreaPanel
     */
    public PlantformManagmentJPanel(EcoSystem system,UserAccount admin,UserControlOrganization org) {
        initComponents();
        this.system=system;
        this.admin=admin;
        this.userOrg = org;
        loadTable();
        initManagementTypeComboBox();
        jComboBox.setSelectedIndex(0);

        javax.swing.SwingUtilities.invokeLater(() -> loadTable());
    }
    private void initManagementTypeComboBox() {
    jComboBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] { "All", "User Control", "Content Control" }
        )
    );

    // ✅ 默认选中 All
    jComboBox.setSelectedIndex(0);
}    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagment = new javax.swing.JTable();
        btnCreatNewAccount = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchByID = new javax.swing.JLabel();
        fieldUserAccountName = new javax.swing.JTextField();
        btnSearchByUserAccountName = new javax.swing.JButton();
        btnSearchByManagementType = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        tblManagment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Name", "Status", "Status", "null"
            }
        ));
        jScrollPane1.setViewportView(tblManagment);
        if (tblManagment.getColumnModel().getColumnCount() > 0) {
            tblManagment.getColumnModel().getColumn(4).setMinWidth(0);
            tblManagment.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblManagment.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnCreatNewAccount.setText("Create new Account");
        btnCreatNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatNewAccountActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("PlantformManagement");

        SearchByID.setText("Search by Name");

        fieldUserAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserAccountNameActionPerformed(evt);
            }
        });

        btnSearchByUserAccountName.setText("Search");
        btnSearchByUserAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByUserAccountNameActionPerformed(evt);
            }
        });

        btnSearchByManagementType.setText("Search by Type");
        btnSearchByManagementType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByManagementTypeActionPerformed(evt);
            }
        });

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchByID)
                        .addGap(4, 4, 4)
                        .addComponent(fieldUserAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByUserAccountName)
                        .addGap(69, 69, 69)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchByManagementType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreatNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchByID)
                    .addComponent(fieldUserAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByUserAccountName)
                    .addComponent(jLabel1)
                    .addComponent(btnSearchByManagementType)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen)
                    .addComponent(btnClose)
                    .addComponent(btnCreatNewAccount))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
              int row = tblManagment.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select an account.");
        return;
    }

    // 第 5 列藏的是 UserAccount 对象
    UserAccount ua = (UserAccount) tblManagment.getValueAt(row, 4);

    if (ua == null) {
        JOptionPane.showMessageDialog(this, "Internal error: user not found.");
        return;
    }

    // 已经是 ACTIVE
    if ("ACTIVE".equalsIgnoreCase(ua.getStatus())) {
        JOptionPane.showMessageDialog(this,
                "This account is already ACTIVE.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 不能把自己关了再开（可选保护）
    if (admin != null && ua.getUsername().equals(admin.getUsername())) {
        JOptionPane.showMessageDialog(this,
                "You cannot modify your own account status here.",
                "Permission Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 修改状态
    ua.setStatus("ACTIVE");

    // 写回 CSV
    basement_class.DAO.UserAccountDAO dao = new basement_class.DAO.UserAccountFileDAO();
    dao.saveAll(system.getUserAccountDirectory().getUserAccounts());

    JOptionPane.showMessageDialog(this,
            "Account [" + ua.getUsername() + "] is now ACTIVE.");

    // 刷新表格
    loadTable();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
          int row = tblManagment.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select an account.");
        return;
    }

    UserAccount ua = (UserAccount) tblManagment.getValueAt(row, 4);

    if (ua == null) {
        JOptionPane.showMessageDialog(this, "Internal error: user not found.");
        return;
    }

    // 不允许关掉自己（防止把自己锁出系统）
    if (admin != null && ua.getUsername().equals(admin.getUsername())) {
        JOptionPane.showMessageDialog(this,
                "You cannot SUSPEND your own account.",
                "Permission Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 可以视情况禁止关关键账号，例如 system admin / super platform admin
    if ("platformadmin".equalsIgnoreCase(ua.getUsername())
            || "s".equalsIgnoreCase(ua.getUsername())) {
        JOptionPane.showMessageDialog(this,
                "This core admin account cannot be suspended.",
                "Permission Denied",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!"ACTIVE".equalsIgnoreCase(ua.getStatus())) {
        JOptionPane.showMessageDialog(this,
                "This account is already not ACTIVE.\nCurrent status: " + ua.getStatus(),
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure to suspend account [" + ua.getUsername() + "] ?",
            "Confirm Suspend",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    // 修改状态
    ua.setStatus("SUSPENDED");

    // 写回 CSV
    basement_class.DAO.UserAccountDAO dao = new basement_class.DAO.UserAccountFileDAO();
    dao.saveAll(system.getUserAccountDirectory().getUserAccounts());

    JOptionPane.showMessageDialog(this,
            "Account [" + ua.getUsername() + "] is now SUSPENDED.");

    // 刷新表格
    loadTable();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCreatNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatNewAccountActionPerformed
              Window parentWindow = SwingUtilities.getWindowAncestor(this);

    NewPlatformAccountDialog dialog =
            new NewPlatformAccountDialog(parentWindow, system);

    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    if (dialog.isSucceeded()) {
        // ✅ 创建成功后刷新表格
        loadTable();
    }
    }//GEN-LAST:event_btnCreatNewAccountActionPerformed

    private void fieldUserAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserAccountNameActionPerformed

    private void btnSearchByUserAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByUserAccountNameActionPerformed
                String name = fieldUserAccountName.getText().trim();
    String selectedType = jComboBox.getSelectedItem().toString();


    if ("All".equalsIgnoreCase(selectedType)) {
        loadTable(name, null);       // 显示全部
    } else {
        loadTable(name, selectedType); // 按 User Control / Content Control 过滤
    }
    }//GEN-LAST:event_btnSearchByUserAccountNameActionPerformed

    private void btnSearchByManagementTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByManagementTypeActionPerformed
              String name = fieldUserAccountName.getText().trim();

    String selectedType = jComboBox.getSelectedItem().toString();

    // ✅ 如果选的是 All，相当于不加 org 过滤
    if ("All".equalsIgnoreCase(selectedType)) {
        loadTable(name, null);
    } else {
        loadTable(name, selectedType);
    }
    }//GEN-LAST:event_btnSearchByManagementTypeActionPerformed
    
    
    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchByID;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreatNewAccount;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSearchByManagementType;
    private javax.swing.JButton btnSearchByUserAccountName;
    private javax.swing.JTextField fieldUserAccountName;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManagment;
    // End of variables declaration//GEN-END:variables

    private void loadTable(String usernameFilter, String orgFilter) {
         DefaultTableModel model = (DefaultTableModel) tblManagment.getModel();
    model.setRowCount(0);

    String nameFilter = (usernameFilter == null || usernameFilter.isEmpty())
            ? null : usernameFilter.toLowerCase();

    String orgNameFilter = (orgFilter == null || orgFilter.isEmpty())
            ? null : orgFilter.toLowerCase();

    for (Network n : system.getNetworks()) {
        for (Enterprise e : n.getEnterprises()) {

            if (!"Platform Management".equals(e.getName())) continue;

            for (Organization org : e.getOrganizations()) {

                for (UserAccount ua : org.getUserAccountDirectory().getUserAccounts()) {

                    // 🔍 用户名过滤
                    if (nameFilter != null &&
                        !ua.getUsername().toLowerCase().contains(nameFilter)) {
                        continue;
                    }

                    // 🔍 组织过滤
                    if (orgNameFilter != null &&
                        !org.getName().toLowerCase().contains(orgNameFilter)) {
                        continue;
                    }

                    Object[] row = new Object[5];
                    row[0] = org.getName();   // Type
                    row[1] = ua.getUsername();
                    row[2] = ua.getStatus();
                    row[3] = ua.getRole() == null
                            ? "N/A"
                            : ua.getRole().getClass().getSimpleName();
                    row[4] = ua;             // ✅ 隐藏对象

                    model.addRow(row);
                }
            }
        }
    }
    }

    private void loadTable() {
        loadTable(null,null);
    }

    private static class NewPlatformAccountDialog extends JDialog {

    private final EcoSystem system;
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JComboBox<String> cmbOrgType;
    private boolean succeeded = false;

    public NewPlatformAccountDialog(Window parent, EcoSystem system) {
        super(parent, "Create Platform Account", ModalityType.APPLICATION_MODAL);
        this.system = system;
        initUI();
    }

    private void initUI() {
        txtUsername = new JTextField(15);
        txtPassword = new JPasswordField(15);
        cmbOrgType = new JComboBox<>(new String[] {
                "User Control",
                "Content Control"
        });

        javax.swing.JPanel form = new javax.swing.JPanel(new GridLayout(3, 2, 5, 5));
        form.add(new javax.swing.JLabel("Username:"));
        form.add(txtUsername);
        form.add(new javax.swing.JLabel("Password:"));
        form.add(txtPassword);
        form.add(new javax.swing.JLabel("Organization:"));
        form.add(cmbOrgType);

        javax.swing.JButton btnOk = new javax.swing.JButton("Create");
        javax.swing.JButton btnCancel = new javax.swing.JButton("Cancel");

        btnOk.addActionListener(e -> onCreate());
        btnCancel.addActionListener(e -> {
            succeeded = false;
            dispose();
        });

        javax.swing.JPanel btnPanel = new javax.swing.JPanel();
        btnPanel.add(btnOk);
        btnPanel.add(btnCancel);

        this.setLayout(new BorderLayout(10, 10));
        this.add(form, BorderLayout.CENTER);
        this.add(btnPanel, BorderLayout.SOUTH);

        this.pack();
    }

    public boolean isSucceeded() {
        return succeeded;
    }

    private void onCreate() {

        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String orgType = (String) cmbOrgType.getSelectedItem();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password are required.");
            return;
        }

        if (system.getUserAccountDirectory().findByUsername(username) != null) {
            JOptionPane.showMessageDialog(this, "Username already exists.");
            return;
        }

        Organization targetOrg = findTargetOrganization(orgType);
        if (targetOrg == null) {
            JOptionPane.showMessageDialog(this, "Target organization not found.");
            return;
        }

        PlatformAdminAccount ua = new PlatformAdminAccount();
        ua.setUserId("PM-" + UUID.randomUUID().toString().substring(0, 8));
        ua.setUsername(username);
        ua.setPasswordHash(password);
        ua.setEmail(username + "@platform.com");
        ua.setPhoneNumber("N/A");
        ua.setOrganizationId(targetOrg.getName());
        ua.setStatus("ACTIVE");

        if (targetOrg instanceof UserControlOrganization) {
            ua.setRole(new AccountAdminRole());
        } else if (targetOrg instanceof ContentControlOrganization) {
            ua.setRole(new ContentModeratorRole());
        }

        system.getUserAccountDirectory().addUserAccount(ua);
        targetOrg.getUserAccountDirectory().addUserAccount(ua);

        UserAccountDAO dao = new UserAccountFileDAO();
        dao.saveAll(system.getUserAccountDirectory().getUserAccounts());

        JOptionPane.showMessageDialog(this, "Account created successfully!");
        succeeded = true;
        dispose();
    }

    private Organization findTargetOrganization(String orgType) {

        for (Network n : system.getNetworks()) {
            for (Enterprise e : n.getEnterprises()) {

                if (!"Platform Management".equals(e.getName())) continue;

                for (Organization org : e.getOrganizations()) {

                    if ("User Control".equals(orgType)
                            && org instanceof UserControlOrganization) {
                        return org;
                    }

                    if ("Content Control".equals(orgType)
                            && org instanceof ContentControlOrganization) {
                        return org;
                    }
                }
            }
        }
        return null;
    }
}
}
