/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import basement_class.EcoSystem;
import basement_class.Enterprise_3.Organization.ContentControlOrganization;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.WorkRequest.AccountStatusReviewRequest;
import basement_class.Enterprise_3.WorkRequest.PolicyViolationRequest;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import service.E3.PolicyEnforcementService;
import service.E3.UserManagementService;

/**
 *
 * @author Linyiyang
 */
public class PolicyEnforcementJPanel extends javax.swing.JPanel {
    private EcoSystem system;
    private UserAccount admin;
    private ContentControlOrganization userOrg;

    private PolicyEnforcementService service;
    /**
     * Creates new form AccountAdminWorkAreaPanel
     */
    public PolicyEnforcementJPanel(EcoSystem system,UserAccount admin,ContentControlOrganization org) {
        initComponents();

        this.system = system;
        this.admin = admin;
        this.userOrg = org;
        this.service = new PolicyEnforcementService();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnDescpriton = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldID2 = new javax.swing.JTextField();
        btnSearchByRequestID2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSearchByUserName2 = new javax.swing.JButton();
        fieldUserName2 = new javax.swing.JTextField();
        SearchByID2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Target User", "Category", "Status", "Object"
            }
        ));
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(4).setMinWidth(0);
            tblUser.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblUser.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnDescpriton.setText("Descpriton");
        btnDescpriton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescpritonActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnAccept.setText("Accepet");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("PolicyEnforcement");

        fieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldID2ActionPerformed(evt);
            }
        });

        btnSearchByRequestID2.setText("Search");
        btnSearchByRequestID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByRequestID2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search by User");

        btnSearchByUserName2.setText("Search");
        btnSearchByUserName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByUserName2ActionPerformed(evt);
            }
        });

        fieldUserName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserName2ActionPerformed(evt);
            }
        });

        SearchByID2.setText("Search by ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchByID2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByRequestID2)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByUserName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDescpriton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchByID2)
                        .addComponent(fieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchByRequestID2)
                        .addComponent(jLabel3)
                        .addComponent(btnSearchByUserName2)
                        .addComponent(fieldUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject)
                    .addComponent(btnDescpriton))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
            PolicyViolationRequest req = getSelectedRequest();
             if (req == null) return;

            // ✅ 当前登录管理员
            UserAccount admin = this.admin;

             int confirm = JOptionPane.showConfirmDialog(
                this,
                "Approve this violation request?",
                "Confirm",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        // ✅ 审计版 Service（必须传 admin）
        service.approveViolation(system, req, admin);

        JOptionPane.showMessageDialog(this, "Request approved and processed.");
        loadTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed

       PolicyViolationRequest req = getSelectedRequest();
    if (req == null) return;

    // ✅ 当前登录管理员
    UserAccount admin = this.admin;

    String reason = JOptionPane.showInputDialog(
            this,
            "Enter rejection reason:",
            "Rejection Reason",
            JOptionPane.PLAIN_MESSAGE
    );

    if (reason == null || reason.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Rejection reason cannot be empty.");
        return;
    }

    // ✅ 二次确认
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm rejection with reason:\n\n" + reason,
            "Confirm Rejection",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    // ✅ 审计版 Service（必须传 admin + reason）
    service.rejectViolation(req, admin, reason);

    JOptionPane.showMessageDialog(this, "Request rejected.");
    loadTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnDescpritonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescpritonActionPerformed
        PolicyViolationRequest req = getSelectedRequest();
    if (req == null) return;

    // 创建一个弹窗
    JDialog dialog = new JDialog((java.awt.Frame) null, "Violation Details", true);
    dialog.setSize(600, 800);
    dialog.setLayout(new BorderLayout());

    // ================== 上半部分：文字信息 =====================
    JTextArea text = new JTextArea();
    text.setEditable(false);
    text.setLineWrap(true);
    text.setWrapStyleWord(true);

    StringBuilder sb = new StringBuilder();
    sb.append("Reporter: ").append(req.getReporter().getUsername()).append("\n");
    sb.append("Target User: ").append(req.getTargetUser().getUsername()).append("\n\n");
    sb.append("Category: ").append(req.getDisplayCategory()).append("\n\n");
    sb.append("Description:\n").append(req.getViolationInfo()).append("\n\n");

    if (req.getListing() != null) {
        sb.append("Related Listing: ").append(req.getListing().getTitle()).append("\n\n");
    }

    text.setText(sb.toString());

    JScrollPane textScroll = new JScrollPane(text);
    textScroll.setPreferredSize(new Dimension(580, 200));
    dialog.add(textScroll, BorderLayout.NORTH);

    // ================== 下半部分：图片证据 =====================
    JPanel imagePanel = new JPanel();
    imagePanel.setLayout(new BoxLayout(imagePanel, BoxLayout.Y_AXIS));

    if (req.getEvidencePaths().isEmpty()) {

        JLabel noImg = new JLabel("No evidence provided.");
        imagePanel.add(noImg);

    } else {
        for (String path : req.getEvidencePaths()) {
            try {
                ImageIcon icon = new ImageIcon(path);

                // 自动缩放图片（最大宽度 500）
                Image scaled = icon.getImage().getScaledInstance(
                        500,
                        -1,
                        Image.SCALE_SMOOTH
                );

                JLabel imgLabel = new JLabel(new ImageIcon(scaled));
                imgLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));

                imagePanel.add(imgLabel);

            } catch (Exception e) {
                imagePanel.add(new JLabel("Failed to load image: " + path));
            }
        }
    }

    JScrollPane imgScroll = new JScrollPane(imagePanel);
    dialog.add(imgScroll, BorderLayout.CENTER);

    // 显示弹窗
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btnDescpritonActionPerformed

    private void fieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldID2ActionPerformed

    private void btnSearchByRequestID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByRequestID2ActionPerformed
        String input = fieldID2.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Request ID.");
        return;
    }

    java.util.List<PolicyViolationRequest> result = new java.util.ArrayList<>();

    for (WorkRequest wr : userOrg.getWorkRequestDirectory().getRequestList()) {
        if (wr instanceof PolicyViolationRequest) {
            PolicyViolationRequest req = (PolicyViolationRequest) wr;

            if ("Pending".equalsIgnoreCase(req.getStatus()) &&
                req.getId().equalsIgnoreCase(input)) {
                result.add(req);
                break; // ✅ ID 唯一
            }
        }
    }

    if (result.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching Request ID found.");
    }

    refreshTable(result);

    // ✅ 搜索后自动清空
    fieldUserName2.setText("");

    }//GEN-LAST:event_btnSearchByRequestID2ActionPerformed

    private void btnSearchByUserName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByUserName2ActionPerformed
          String keyword = fieldUserName2.getText().trim().toLowerCase();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username.");
        return;
    }

    java.util.List<PolicyViolationRequest> result = new java.util.ArrayList<>();

    for (WorkRequest wr : userOrg.getWorkRequestDirectory().getRequestList()) {
        if (wr instanceof PolicyViolationRequest) {
            PolicyViolationRequest req = (PolicyViolationRequest) wr;

            if ("Pending".equalsIgnoreCase(req.getStatus())) {
                String username = req.getTargetUser()
                                     .getUsername()
                                     .toLowerCase();

                if (username.contains(keyword)) {
                    result.add(req);
                }
            }
        }
    }

    if (result.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching user found.");
    }

    refreshTable(result);

    // ✅ 搜索后自动清空
    fieldUserName2.setText("");
    }//GEN-LAST:event_btnSearchByUserName2ActionPerformed

    private void fieldUserName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserName2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchByID2;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDescpriton;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSearchByRequestID2;
    private javax.swing.JButton btnSearchByUserName2;
    private javax.swing.JTextField fieldID2;
    private javax.swing.JTextField fieldUserName2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        java.util.List<PolicyViolationRequest> list = new java.util.ArrayList<>();

        for (WorkRequest wr : userOrg.getWorkRequestDirectory().getRequestList()) {
            if (wr instanceof PolicyViolationRequest) {
                list.add((PolicyViolationRequest) wr);
            }
        }

        refreshTable(list);   // ✅ 统一入口
    }
    

    private void refreshTable(java.util.List<PolicyViolationRequest> list) {
    DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
    model.setRowCount(0);

    for (PolicyViolationRequest req : list) {

        // ✅ 只显示 Pending
        if (!"Pending".equalsIgnoreCase(req.getStatus())) continue;

        model.addRow(new Object[]{
            req.getId(),
            req.getTargetUser().getUsername(),
            req.getDisplayCategory(),
            req.getStatus(),
            req
        });
    }
}

    private PolicyViolationRequest getSelectedRequest() {
        int row = tblUser.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return null;
        }
        return (PolicyViolationRequest) tblUser.getValueAt(row, 4);
    }
}