/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.WorkRequest.RegistrationApprovalRequest;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.E3.RegistrationService;

/**
 *
 * @author Administrator
 */
public class RegistrationReviewJPanel extends javax.swing.JPanel {
    private UserAccount userAccount;
    private UserControlOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private RegistrationService regService = new RegistrationService();
    /**
     * Creates new form RegistrationReviewJPanel

     */
    public RegistrationReviewJPanel(UserAccount userAccount,Organization org,Enterprise enterprise,EcoSystem system) {
        initComponents();

        this.userAccount = userAccount;
        this.organization = (UserControlOrganization) org;
        this.enterprise = enterprise;
        this.system = system;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldID2 = new javax.swing.JTextField();
        btnSearchByRequestID2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSearchByUserName2 = new javax.swing.JButton();
        fieldUserName2 = new javax.swing.JTextField();
        SearchByID2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "UserName", "Email", "Status", "request"
            }
        ));
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(4).setMinWidth(0);
            tblUser.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblUser.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("RegistrationReview");

        fieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldID2ActionPerformed(evt);
            }
        });

        btnSearchByRequestID2.setText("Search");
        btnSearchByRequestID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByRequestID2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search by User");

        btnSearchByUserName2.setText("Search");
        btnSearchByUserName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByUserName2ActionPerformed(evt);
            }
        });

        fieldUserName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserName2ActionPerformed(evt);
            }
        });

        SearchByID2.setText("Search by ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchByID2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByRequestID2)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByUserName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchByID2)
                        .addComponent(fieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchByRequestID2)
                        .addComponent(jLabel3)
                        .addComponent(btnSearchByUserName2)
                        .addComponent(fieldUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
             int row = tblUser.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a request to approve.");
        return;
    }

    RegistrationApprovalRequest req =
            (RegistrationApprovalRequest) tblUser.getValueAt(row, 4);

    if (!req.getStatus().equalsIgnoreCase("PENDING")) {
        JOptionPane.showMessageDialog(this, "This request has already been processed.");
        return;
    }

    UserAccount admin = this.userAccount;

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm approve this registration request?",
            "Confirm Approval",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    RegistrationService service = new RegistrationService();
    service.approve(req, admin);

    JOptionPane.showMessageDialog(this, "User approved successfully!");

    populateTable();  
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int row = tblUser.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a registration request first.");
        return;
    }

    RegistrationApprovalRequest req =
            (RegistrationApprovalRequest) tblUser.getValueAt(row, 4);

    if (!req.getStatus().equalsIgnoreCase("PENDING")) {
        JOptionPane.showMessageDialog(this, "This request has already been processed.");
        return;
    }

    UserAccount admin = this.userAccount;

    String reason = JOptionPane.showInputDialog(
            this,
            "Please enter the reason for rejection:",
            "Rejection Reason",
            JOptionPane.PLAIN_MESSAGE
    );

    if (reason == null || reason.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Rejection cancelled.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm rejection with reason:\n\n" + reason,
            "Confirm Rejection",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Rejection cancelled.");
        return;
    }

    req.setReason(reason);

    RegistrationService service = new RegistrationService();
    service.reject(req, admin, reason);

    JOptionPane.showMessageDialog(this, "Registration request rejected.");

    populateTable();   
    }//GEN-LAST:event_btnRejectActionPerformed

    private void fieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldID2ActionPerformed

    private void btnSearchByRequestID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByRequestID2ActionPerformed
         String input = fieldID2.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Request ID.");
        return;
    }

    java.util.List<RegistrationApprovalRequest> result = new java.util.ArrayList<>();

    for (WorkRequest wr : organization.getWorkRequestDirectory().getRequestList()) {
        if (wr instanceof RegistrationApprovalRequest) {
            RegistrationApprovalRequest rar = (RegistrationApprovalRequest) wr;

            if ("PENDING".equalsIgnoreCase(rar.getStatus()) &&
                rar.getId().equalsIgnoreCase(input)) {
                result.add(rar);
                break; // ✅ ID 唯一
            }
        }
    }

    if (result.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching Request ID found.");
    }

    refreshTable(result);

    fieldID2.setText("");

    }//GEN-LAST:event_btnSearchByRequestID2ActionPerformed

    private void btnSearchByUserName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByUserName2ActionPerformed
                String keyword = fieldUserName2.getText().trim().toLowerCase();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username.");
        return;
    }

    java.util.List<RegistrationApprovalRequest> result = new java.util.ArrayList<>();

    for (WorkRequest wr : organization.getWorkRequestDirectory().getRequestList()) {
        if (wr instanceof RegistrationApprovalRequest) {
            RegistrationApprovalRequest rar = (RegistrationApprovalRequest) wr;

            if ("PENDING".equalsIgnoreCase(rar.getStatus())) {
                String username = rar.getNewUser()
                                     .getUsername()
                                     .toLowerCase();

                if (username.contains(keyword)) {
                    result.add(rar);
                }
            }
        }
    }

    if (result.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching user found.");
    }

    refreshTable(result);

    fieldUserName2.setText("");
    }//GEN-LAST:event_btnSearchByUserName2ActionPerformed

    private void fieldUserName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserName2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchByID2;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSearchByRequestID2;
    private javax.swing.JButton btnSearchByUserName2;
    private javax.swing.JTextField fieldID2;
    private javax.swing.JTextField fieldUserName2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
    java.util.List<RegistrationApprovalRequest> list = new java.util.ArrayList<>();

    for (WorkRequest req : organization.getWorkRequestDirectory().getRequestList()) {
        if (req instanceof RegistrationApprovalRequest) {
            list.add((RegistrationApprovalRequest) req);
        }
    }

    refreshTable(list);   
}

    private void refreshTable(java.util.List<RegistrationApprovalRequest> list) {
    DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
    model.setRowCount(0);

    for (RegistrationApprovalRequest rar : list) {

        if (!"PENDING".equalsIgnoreCase(rar.getStatus())) continue;

        Object[] row = new Object[]{
                rar.getId(),
                rar.getNewUser().getUsername(),
                rar.getNewUser().getEmail(),
                rar.getStatus(),
                rar
        };

        model.addRow(row);
        }
    }
}
