/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Enterprise3;

import basement_class.EcoSystem;
import basement_class.Enterprise;
import basement_class.Enterprise_3.Organization.UserControlOrganization;
import basement_class.Enterprise_3.WorkRequest.RegistrationApprovalRequest;
import basement_class.Organization;
import basement_class.UserAccount;
import basement_class.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.E3.RegistrationService;

/**
 *
 * @author Administrator
 */
public class RegistrationReviewJPanel extends javax.swing.JPanel {
    private UserAccount userAccount;
    private UserControlOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private RegistrationService regService = new RegistrationService();
    /**
     * Creates new form RegistrationReviewJPanel

     */
    public RegistrationReviewJPanel(UserAccount userAccount,Organization org,Enterprise enterprise,EcoSystem system) {
        initComponents();

        this.userAccount = userAccount;
        this.organization = (UserControlOrganization) org;
        this.enterprise = enterprise;
        this.system = system;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "UserName", "Email", "Status", "request"
            }
        ));
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(4).setMinWidth(0);
            tblUser.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblUser.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
            int row = tblUser.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a request to approve.");
        return;
    }

    RegistrationApprovalRequest req =
            (RegistrationApprovalRequest) tblUser.getValueAt(row, 4);

    if (!req.getStatus().equalsIgnoreCase("PENDING")) {
        JOptionPane.showMessageDialog(this, "This request has already been processed.");
        return;
    }

    // 调用 service 完成逻辑
    RegistrationService service = new RegistrationService();
    service.approve(req);

    JOptionPane.showMessageDialog(this, "User approved successfully!");

    populateTable(); // 自动刷新，审批完成后从表格消失
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
       int row = tblUser.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a registration request first.");
            return;
        }

        // 从隐藏列取出 request 对象
        RegistrationApprovalRequest req =
            (RegistrationApprovalRequest) tblUser.getValueAt(row, 4);

        if (!req.getStatus().equalsIgnoreCase("PENDING")) {
            JOptionPane.showMessageDialog(this, "This request has already been processed.");
            return;
        }

        // 1. 输入拒绝理由
        String reason = JOptionPane.showInputDialog(
                this,
                "Please enter the reason for rejection:",
                "Rejection Reason",
                JOptionPane.PLAIN_MESSAGE
        );

        // 用户取消 或输入空
        if (reason == null || reason.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rejection cancelled.");
            return;
        }

        // 2. 再次确认
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm rejection with reason:\n\n" + reason,
            "Confirm Rejection",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Rejection cancelled.");
            return;
        }

        // 3. 记录拒绝理由
        req.setReason(reason);

        // 4. 调用你写好的业务层逻辑（service）
        RegistrationService service = new RegistrationService();
        service.reject(req, reason);

        // 5. 通知 & 刷新 Table
        JOptionPane.showMessageDialog(this, "Registration request rejected.");
        populateTable();   // 或你自己的 loadTable()
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);
        
        for (WorkRequest req : organization.getWorkRequestDirectory().getRequestList()) {
            if (req instanceof RegistrationApprovalRequest) {
                RegistrationApprovalRequest rar = (RegistrationApprovalRequest) req;
                
                 if(!req.getStatus().equalsIgnoreCase("PENDING")) {
                continue;
                }
                 
                Object[] row = new Object[]{
                        rar.getId(),
                        rar.getNewUser().getUsername(),
                        rar.getNewUser().getEmail(),
                        rar.getStatus(),
                        rar
                };
                model.addRow(row);
            }
        }
    }
}
